### ISSUE TITLE
Timeout or no reply using currentLocation or currentLocation

### ISSUE THREAD

**Issue by Lao-Ben** [malcommac/SwiftLocation#1]
Each time I try to get location using currentLocation I get a timeout error. With currentLocation I get nothing, neither onSuccess or onFail are called.
Is it supposed to work or it's still in development?

**Comment by malcommac** [comment]
Hi,
Thank you for your report. In fact I've found a possible problem accessing hardware after first user authorization session.Now it should works fine.
(Be sure to add appropriate keys to your app's Info.plist and add a simulated location if you are using it from your iOS simulator).
Build 0.1.1 was just posted to CocoaPods. Tell me if it's okay for you.

**Comment by Lao-Ben** [comment]
Hi,
I tried again with 0.1.2 build but it's the same, I have now problem with default LocationManager or other wrappers. I don't have time to track the problem now, but when I have some I will try again and let you now if I can find what cause those issues.

**Comment by malcommac** [comment]
I'll be out for holidays two weeks starting today. If you have some time to make a small test project to I'll be happy to fix it. Thank you again. See you soon.

**Comment by malcommac** [comment]
Fixed in c82cf94eed9c399fe8bccc89ced5019650e84bd0
