### ISSUE TITLE
onAuthorizationDidChange not called (and never called) on specific flow

### ISSUE THREAD

**Issue by bphenriques** [malcommac/SwiftLocation#102]
Environment:
- Version 1.1.1
- Swift 3
- iPhone 4S 8.4

I am displaying a alert to open the app settings when the status is different than the one required (.alwaysInUse). The handler is being called when I swap between an incorrect value (`!= .alwaysInUse`) and (`.alwaysInUse`) but is not called between two incorrect values. This is important because I am using the handler to open an alert.

Reproduce:
1. Open app and authorise location
2. Go to settings app (app suspended and change to when in use or never)
3. Go to app and the handler `onAuthorizationDidChange` is called
4. Go to settings app and change to the other non-always option
5. Go back to app and the handler is not called
6. From now on, the `onAuthorizationDidChange` event handler is never called

**Comment by malcommac** [comment]
Hi @bphenriques,
This not seems a bug; in fact when an error occurs while performing a request the request itself is aborted and removed from the queue.
You should re-add it manually.

**Comment by malcommac** [comment]
I'm working around it in order to provide a recovery on error feature. I'll update this thread soon as I can.

**Comment by bphenriques** [comment]
Hey @malcommac , that behaviour was not clear for me. I will attempt to re-observe on viewWillAppear and see if it solves the issue

**Comment by Alex293** [comment]
So if I want to ignore errors and keep updated I should start another request in the error callback ?
Isn't simple that the request shouldn't be discarded unless we cancel it in the error callback ?

**Comment by bphenriques** [comment]
That was the behaviour I was expecting as well (cancel on viewWillDisappear/deInit)

**Comment by malcommac** [comment]
Since  2.x branch you can observe the authorization status for each request:

```swift
let request = Location.getLocation...
// callback is called on main thread by reporting previous and current authorization status
request.register(observer: LocObserver.onAuthDidChange(.main, { (request, oldAuth, newAuth) in
    print("Authorization moved from \(oldAuth) to \(newAuth)")
}))
```


Please notice: while the overall behaviour is the same, since 2.x branch some API names are changed. Nothing dramatic 👍

**Comment by markst** [comment]
perhaps the readme could be updated:
https://github.com/malcommac/SwiftLocation/#observe-authorization-status-changes
