### ISSUE TITLE
It will wake up the app if it's suspended or killed ?

### ISSUE THREAD

**Issue by youss-cs** [malcommac/SwiftLocation#105]
In my app i need to get location continuously, even if the app is killed or suspended. is that possible ? 
If yes can you provide me how i can set up this please ?

**Comment by Milestacular** [comment]
@youss-cs you can run in background fairly easily, head to the README.md and search in page for background and you'll find what you need fairly quickly. 😊

**Comment by Milestacular** [comment]
Apologies I just realised you meant when the app is closed from the background.

**Comment by youss-cs** [comment]
Yes, is that possible ?

**Comment by ghost** [comment]
@youss-cs are you referring to activating background modes in order to continue receiving the location even if the app is closed? 

<img width="741" alt="screen shot 2017-02-05 at 9 46 01 am" src="https://cloud.githubusercontent.com/assets/15761334/22627020/f76550d8-eb87-11e6-9efd-90e13d0cc01b.png">

**Comment by malcommac** [comment]
The only supported way to have background even if the app is terminated is to register for `significant` location updates or by registering monitored regions.
What accuracy do you need?

**Comment by youss-cs** [comment]
I need new location every 1min, significant location give new location only if user move 500m so it's not what i need.

**Comment by malcommac** [comment]
There is not an official way to do continuous location monitoring in background for an unlimited time.
You could create a background task and register a region; once the device exit from the region the app is resumed/restarted and in your AppDelegate's `didFinishLaunching` func you can register another region...and so on.
This is one of the trick you may use but energy consuption may be huge and Apple may not be happy to see it.
