### ISSUE TITLE
Split Location and Beacon support

### ISSUE THREAD

**Issue by dbpfindexp** [malcommac/SwiftLocation#107]
To keep the pod super lite any plans on splitting up Beacon Support & plain Location stuff on it's own.  I really don't need the extra Beacon stuff and just want a super lite Location pod.

**Comment by malcommac** [comment]
Yeah the next release (in 2.0.0 branch) will contains only location services monitor.
Beacon services will be splitted in another framework.

**Comment by malcommac** [comment]
I've released an 1.2.0 update which remove temporary the bluetooth from the spec.
