### ISSUE TITLE
kCLErrorDomain error 0

### ISSUE THREAD

**Issue by nico75005** [malcommac/SwiftLocation#108]
I have an iPad mini retina without a SIM card but the iPad is connected to my Wifi. I'm currently inside and my location request uses an accuracy of `.house`, a frequency of `.oneShot`, with a `timeout` of 120.

When I try to get the location, after about 25 seconds, I get the following error:

```
Location manager error: The operation couldn’t be completed. (kCLErrorDomain error 0.)
```

But when I get an accuracy of `.block`, I get the location almost straight away.

Can someone explain me why I can't get the location and what is this error?

**Comment by malcommac** [comment]
kCLErrorDomain 0 means the location could not be determined.

```
kCLErrorLocationUnknown The location manager was unable to obtain a location value right now.Available in iPhone OS 2.0 and later. Declared in CLError.h.
```

I would guess the most likely cause is that the location manager is using WiFi to triangulate the location .Have you got the same problems with standard CLLocationManager?
Give a try to version 2.0.1 and tell me if it works for you.
