### ISSUE TITLE
app crash when Location permission "Not Determined"

### ISSUE THREAD

**Issue by sunweifeng** [malcommac/SwiftLocation#109]
app crash when Location permission "Not Determined"

code here: 
```swift
Location.getLocation(accuracy: .any, frequency: .oneShot, timeout: 30, success: {(request, location) -> (Void) in
  // code
}) {(request, location, error) -> (Void) in
  // code
}
```

**Comment by malcommac** [comment]
Hi @sunweifeng;
can you describe the situation and the crash?
How you got the "Not Determined" state and what's the stack trace of the crash?
Thank you

**Comment by sunweifeng** [comment]
Hi @malcommac 

Issue solved by Clean action, maybe some cache file cause this issue, because i updated the library from  version 1.xx to 2.xx .
