### ISSUE TITLE
Background location (.significant) update is on the on (.oneShot) Doesn't work

### ISSUE THREAD

**Issue by O-mkar** [malcommac/SwiftLocation#111]
I have registered Background location update in application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?)

```
 Location.getLocation(accuracy: .house, frequency: .significant, success: { (request, location) in
                print("A new update of background location is available: \(location)")
         
            }) { (request, last, error) in
                request.cancel() // stop continous location monitoring on error
            }
```

If it is running Oneshot doesn't work.

**Comment by malcommac** [comment]
Significant location monitoring may not return the accuracy you expect; in your example you are requesting an high precision location and probability due to significant monitoring constraints you will never get.
Try to set it to `any` and tell me if you get some sort of results.

**Comment by O-mkar** [comment]
@malcommac Okay
