### ISSUE TITLE
High accuracy is simply not working on devices

### ISSUE THREAD

**Issue by mamdouhweb** [malcommac/SwiftLocation#113]
Hello there!

I'm running this library with `.house` accuracy and it simply hangs if I'm testing on my device (iPhone 7) However, it works perfectly with the simulator.
I tried the `.city` accuracy and it worked perfectly on both, the simulator and the device.

I can't tell exactly what's wrong, as the onError part of the location request is even being called.
I can see that the request is being added through Location.onAddNewRequest.

Thanks!

**Comment by Ekhoo** [comment]
I have the same issue. Did found something ?

**Comment by Ekhoo** [comment]
@malcommac can you please fix the high accuracy ? For me, `.room` and `.house` don't work.

**Comment by malcommac** [comment]
![img_0504](https://cloud.githubusercontent.com/assets/235645/24699597/d7a142ca-19f4-11e7-957c-a57f692886a9.PNG)

Just fixed in 2.0.2.
(example included, the upper field receive only valid locations, the bottom side receive all locations. It takes a while to receive the best accuracy sometimes).
