### ISSUE TITLE
Background Location Updates 

### ISSUE THREAD

**Issue by umutdonmez8** [malcommac/SwiftLocation#114]
Hi,

I have a question about this background issue. In swiftLocation documentation Location.allowsBackgroundEvents = true code writes for activate background location updates. I integrate SwiftLocation to my new project but, there is not any variable to set allowsBackgroundEvents

When I am trying to get location there is a log like
A new request is added to the queue [LOC:826CB3FC-F0BD-4CB8-B8E2-EB6B598BE02F] - Acc=Room, Fq=Significant. (Status=running, Queued=true) oYn4pRVBj3e56KTO0QXIhgABzT32 An existing request was removed from the queue [LOC:826CB3FC-F0BD-4CB8-B8E2-EB6B598BE02F] - Acc=Room, Fq=Significant. (Status=idle, Queued=false) Location monitoring failed due to an error backgroundModeNotSet

In my info.plist I insert the required background modes and I also open Location updates in Background Modes in Capabilities section.

What can be the problem ?

Thanks for any help

My code is below (taken from Demo project):

`//Taking Location

    Location.onAddNewRequest = { req in
        print("A new request is added to the queue \(req)")
    }
    Location.onRemoveRequest = { req in
        print("An existing request was removed from the queue \(req)")
    }
    
    
    let x = Location.getLocation(accuracy: .room, frequency: .significant, success: { (_, location) in
        print("A new update of location is available: \(location)")
        let longitude = location.coordinate.longitude
        let latitude = location.coordinate.latitude
        self.firebaseManager.setLocation(uid: uid!, longitude: longitude, latitude: latitude)
        
    }) { (request, last, error) in
        request.cancel() // stop continous location monitoring on error
        print("Location monitoring failed due to an error \(error)")
    }
    x.register(observer: LocObserver.onAuthDidChange(.main, { (request, oldAuth, newAuth) in
        print("Authorization moved from \(oldAuth) to \(newAuth)")
    }))

    
    //taking Location end`

**Comment by aliasdoc** [comment]
Hi @umutdonmez8 , you need to set "Background fetch" in capabilities.

**Comment by malcommac** [comment]
As @aliasdoc said you must also enable location UIBackground capabilities
