### ISSUE TITLE
lastLocation, internal ???

### ISSUE THREAD

**Issue by aliasdoc** [malcommac/SwiftLocation#115]
In v2 we can't access to LocationTracker.lastLocation due to internal protection level, why ? Is there another way ?
```shell
'lastLocation' is inaccessible due to 'internal' protection level
```
Thank you.

**Comment by malcommac** [comment]
I've reproduced it but I don't know how to solve; it's a `private(set` and it's the same with `fileprivate(set)`.
I must confess, I'm a bit confused

**Comment by malcommac** [comment]
ok found it must be `public private(set) ...`
Thanks.

**Comment by malcommac** [comment]
Reference commit: https://github.com/malcommac/SwiftLocation/commit/cba21f086588a0171f7d7e78ed3f1963837036d4

**Comment by florianthiel** [comment]
`last` and `bestAccurated` also should be `public private(set)`. Right now they are inaccessible

**Comment by radvansky-tomas** [comment]
Can you commit change ?!
