### ISSUE TITLE
How can i use this for geo reversing with google maps as you wrote we can use

### ISSUE THREAD

**Issue by santhoshs5** [malcommac/SwiftLocation#116]

**Comment by malcommac** [comment]
Can you explain it better?
Would you to reverse geocoding a location coordinate to an address using google maps apis?

**Comment by santhoshs5** [comment]
I was asking How can I get reverse geocoding a location coordinate to an address using google maps apis

**Comment by rujoota** [comment]
@santhoshs5 
Use the following method to use Google placemarks:
Location.reverse(location: loc, using: .google, onSuccess: successHandler, onError: errorHandler)

Make sure you set Location.googleAPIKey and enable proper services in Google developer dashboard.

**Comment by santhoshs5** [comment]
is this method needs to be called on main queue .Because Google mandate call this method on main queue.

**Comment by rujoota** [comment]
Haven't tried that....

**Comment by malcommac** [comment]
Actually I've removed it from current version. I'll update it soon as I can to re-introduce this feature.

**Comment by Saad-Umar** [comment]
Any updates on this one yet? @malcommac

**Comment by malcommac** [comment]
A new version is available on master and supports both reverse geocoding and place autocomplete.
Thanks.
