### ISSUE TITLE
Initialize LocationTracker in background thread will results in a warning

### ISSUE THREAD

**Issue by santhoshs5** [malcommac/SwiftLocation#117]
A location manager (0x1610ab70) was created on a dispatch queue executing on a thread other than the main thread.  It is the developer's responsibility to ensure that there is a run loop running on the thread on which the location manager object is allocated.  In particular, creating location managers in arbitrary dispatch queues (not attached to the main queue) is not supported and will result in callbacks not being received.

**Comment by malcommac** [comment]
Thank you, I've fixed it.
