### ISSUE TITLE
iOS 9 support location update in suspend

### ISSUE THREAD

**Issue by kiokumicu** [malcommac/SwiftLocation#12]
Hi!
You are plan add new param for iOS 9 **allowsBackgroundLocationUpdates** ?
https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/index.html#//apple_ref/occ/instp/CLLocationManager/allowsBackgroundLocationUpdates

**Comment by guillemsole** [comment]
+1
