### ISSUE TITLE
Significant Location Changes don't require UIBackgroundModes key 

### ISSUE THREAD

**Issue by ay8s** [malcommac/SwiftLocation#120]
I believe the logic currently requires it to be enabled however "apps can use the signifiant location change interface to receive location events instead of registering as a background location app."

https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html

Just digging into this after a rejection for having location enabled in background modes when I only need significant changes. 

I've set allowsBackgroundLocationUpdates to false along with adjusting significant to return false within isBackgroundRequest, I still get the location changes when the app is in the background.

**Comment by malcommac** [comment]
Thank you for your feedback. I've removed the request for background modes in significant location request.
