### ISSUE TITLE
Detecting user's activity/motion state

### ISSUE THREAD

**Issue by rujoota** [malcommac/SwiftLocation#121]
Is there a way to detect motion while getting location updates?

In readme, it is mentioned that request.register method can be used for such purposes, but couldn't find much after digging into it.

Also, you need to update readme, all the functions are not applicable for your library's current version.

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
