### ISSUE TITLE
Value of type 'LocationTracker' has no member 'allowsBackgroundEvents' 

### ISSUE THREAD

**Issue by dfsaetamar** [malcommac/SwiftLocation#122]
I have error when using
"Location.allowsBackgroundEvents = true"
Before it worked correctly but apparently no longer works since upgrade to Xcode 8.3.1

Any idea why the error?
Thanks, SwiftLocation is great

**Comment by malcommac** [comment]
`allowsBackgroundEvents` should be set automatically when background monitoring has requested.

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
