### ISSUE TITLE
Value of type '[CLPlacemark]' has no member 'postalCode'

### ISSUE THREAD

**Issue by pbeneteau** [malcommac/SwiftLocation#124]
How can i get the postal code from the CLPlacemark returned by `getPlacemark()` ?

**Comment by pbeneteau** [comment]
What really represents this array?

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
