### ISSUE TITLE
oneShot frequency fires off twice, the second time being a timeout error. (Version 2.0.2)

### ISSUE THREAD

**Issue by dilizarov** [malcommac/SwiftLocation#128]
```
SwiftLocation.Location.getLocation(accuracy: .block, frequency: .oneShot, timeout: 20, success: { (_, location) in
    print("location \(location)")
}) { (request, last, error) in
    print("error \(error)")
}
```

This returns the location for me and then soon after it'll also trigger my error handler.  I've come across different bugs that have led me to update to the latest version, but I'm not feeling confident with this library lately because of the bugs :/

**Comment by dilizarov** [comment]
Nevermind, I realized the error in my ways. Nothing wrong with lib. This was expected behavior.

**Comment by falnatsheh** [comment]
@dilizarov Curious to know what you were doing wrong that caused this behavior. I also starting seeing something similar in 2.0.2.
