### ISSUE TITLE
Can SwiftLocation Framework get related degree from user locatoin to some location?

### ISSUE THREAD

**Issue by SuYungCheng** [malcommac/SwiftLocation#129]
If I know some location(latigude,longitude),
I want to make a Infomation view in my screen like AR,
How can I get the heading to the location, not to the north.
When I face to the location , I want to keep a view in my screen.
when I turn left,the Infomation View move from screen to the right hand.
Thanks!

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
