### ISSUE TITLE
Missing watchOS 2 support

### ISSUE THREAD

**Issue by vernalkick** [malcommac/SwiftLocation#13]
Hey, could you add support for watchOS 2?

```
"platforms": {
  "iOS": "8.0",
  "watchos": "2.0"
}
```

More info: https://medium.com/@JTEhlert/using-cocoapods-with-watchos-2-723b92eae04f

**Comment by carbamide** [comment]
A lot of the apis used in this project aren't available on watchOS 2.  It would be more work to add this than adding that to the podfile.  That said, it would be pretty cool if this were a thing.

**Comment by malcommac** [comment]
What kind of features would you use in WatchOS?
