### ISSUE TITLE
`oneShot` frequency with timeout keeps firing 

### ISSUE THREAD

**Issue by falnatsheh** [malcommac/SwiftLocation#131]
When I try to get `oneShot` location with `timeout` the error closure keeps firing. 

```swift
Location.getLocation(accuracy: .block, frequency: .oneShot, timeout: 5,  success: { (_, location) in
   print("Location Success")
 }) { (_, last, error) in
   print("Location Error")
}
```
I'm using the latest version `2.0.4` and testing on iPhone 7 simulator with `Location -> None` option. Please see attached test project, you could run it and see "Location Error" keeps printing in the logs. 

[TestSwiftLocation.zip](https://github.com/malcommac/SwiftLocation/files/981311/TestSwiftLocation.zip)

**Comment by malcommac** [comment]
Thank you, just fixed https://github.com/malcommac/SwiftLocation/commit/4875ed9acc7a61b0b3e217fc05d220e0b674ec71

**Comment by lastcc** [comment]
@malcommac I think there might be some spelling errors in the documentation:

As I am not a native speaker, the following suggestions might be incorrect:

1. "callback called once the device `did entered into` the region"
seems it should be `did enter into` or just `entered into`

2. "(input params include a `refere` to HeadingRequest and occurred Error)"

3. "`Second options is`: monitor(region:enter:exit:error: `define` the following parameters:"
...missing a `)`

4. there are formatting issues, the code snippets are mixing spaces and tabs. 

5. Background monitoring is a sensitive topic; `efficent` use of device's battery is one of hit point for Apple.

6. "What it does mean?" seems a little weird to me, but I am not a native speaker so I don't know.

7. "to get the most `accurated` result for a limited period of time"

8. "while application` is` in terminated mode."
I assume it could be `was` (?) I'm now reading the section Using Background Task and I am not fully understand it so.

9. "This function also scan for any running ..."
I might use `scans` instead.

**Comment by lastcc** [comment]
@malcommac Sorry I don't understand the following:

"as soon as the device crosses the region you will create another region from the current coordinates while entering and exiting from regions, did update location delegate gets called and you get the updated coordinate while application is in terminated mode."

Does it mean:
In the background task submitted to the operating system, I will create a region monitoring request and submit this request to your framework. As soon as the system -> location framework detects a region change, I will be notified. Then I need to "create another region from the current coordinates" (???)

Sorry can you be so kind and give me some code snippets and explain more detail about this?
