### ISSUE TITLE
Location.getPlacemark error handler accumulated

### ISSUE THREAD

**Issue by Drenov** [malcommac/SwiftLocation#134]
While using **Location.getPlacemark** it is the accumulation of GeocoderRequest`s in Location.pools occurs. Than  failure in for example Location.getPlacemark with disabled geolocation, lead to GeocoderRequest failure completion handlers call in a bunch.

(lldb) po Location.pools
▿ 5 elements
  ▿ 0 : Pool of LocationRequest.Type: 0 total (0 running, 0 paused)
  ▿ 1 : Pool of RegionRequest.Type: 0 total (0 running, 0 paused)
  ▿ 2 : Pool of VisitsRequest.Type: 0 total (0 running, 0 paused)
  ▿ 3 : Pool of GeocoderRequest.Type: 7 total (7 running, 0 paused)
  ▿ 4 : Pool of HeadingRequest.Type: 0 total (0 running, 0 paused)

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
