### ISSUE TITLE
Getting error when trying to clone swiftlocation with cocoapod

### ISSUE THREAD

**Issue by afiq90** [malcommac/SwiftLocation#135]
Hi guys, anyone have any idea why did I got these error ? I'm using xcode 8.3.2

**My pod config :** 
![screen shot 2017-05-15 at 3 19 43 pm](https://cloud.githubusercontent.com/assets/8640517/26046541/f9616b36-3981-11e7-851a-3ec0941a3703.png)

**Pod Error :** 
![swiftlocation error](https://cloud.githubusercontent.com/assets/8640517/26046511/cca55aee-3981-11e7-83b7-1f0667a0459c.png)

Thank you in advance.

**Comment by gsmeros** [comment]
Same issue here

**Comment by gsmeros** [comment]
try this : 

>     pod 'SwiftLocation', :git => 'https://github.com/malcommac/SwiftLocation.git', :branch => 'master'

**Comment by afiq90** [comment]
Thank you, it's working perfectly.

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
