### ISSUE TITLE
NSLocationAlwaysUsageDescription in Info.plist not always recognized

### ISSUE THREAD

**Issue by NathanJang** [malcommac/SwiftLocation#138]
# Steps:
1. Set a description for `NSLocationAlwaysUsageDescription` in `Info.plist`, *without setting `NSLocationWhenInUseUsageDescription`*.
2. Call `Location.getLocation(accuracy:frequency:success:error:)` in `application(_:didFinishLaunchingWithOptions:)` with the frequency as something *other than `.significant`*.

# Expected Result
The app prompts the user for location services "always" (i.e., even when the app is not running), and then calls the `success` callback.

# Actual Result
The `error` callback is called with an error `.missingAuthInInfoPlist`.

# Comments
When I also set the `NSLocationWhenInUseUsageDescription`, the app prompts the user for location services just fine, but only for when the app is running. The `NSLocationAlwaysUsageDescription` key only seems to work for a frequency of `.significant`.

I know it's better practice to only use location services when the app is running, or only allow "always" location services for `.significant` location changes, but the framework shouldn't disallow this, and there are indeed use cases where we want to prompt the user for "always" location services, while performing a precise location measurement (such as a `.oneOff` measurement) initially.

Tested on iOS 10 (simulator and actual devices) with version 2.0.7

**Comment by iDeveloperCom** [comment]
I am developing a tracker app, which has the .continuous mode if the app is in foreground and shown (viewDidAppear) and .significant mode if app is in background. Because the app starts always in foreground mode and the .continuous mode is the one for foreground I never been asked for "always" 

I share the opinion of @NathanJang , you should not prohibit to ask "always" in continuous mode

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
