### ISSUE TITLE
When installing pods, Error Occurs 

### ISSUE THREAD

**Issue by MuhammadMurtazaMemon** [malcommac/SwiftLocation#139]
[!] Error installing SwiftLocation
[!] /usr/local/bin/git clone https://github.com/malcommac/SwiftLocation.git /var/folders/05/qdbzr3rd6t34x70bwjnl2gmh0000gn/T/d20170527-5864-1nkjv0b --template= --single-branch --depth 1 --branch 2.0.2

Cloning into '/var/folders/05/qdbzr3rd6t34x70bwjnl2gmh0000gn/T/d20170527-5864-1nkjv0b'...
warning: Could not find remote branch 2.0.2 to clone.
fatal: Remote branch 2.0.2 not found in upstream origin

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
