### ISSUE TITLE
Minor typo in LocationError

### ISSUE THREAD

**Issue by HansBrende** [malcommac/SwiftLocation#141]
You have 

`case authorizationDenided`

instead of

`case authorizationDenied`

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
