### ISSUE TITLE
How to cancel Location.monitor?

### ISSUE THREAD

**Issue by kohdesmond** [malcommac/SwiftLocation#142]
Hi as the subject title.

How do we stop location.monitor?

I would like to let the region monitoring run on at the background.

and stop it once the app is in the foreground.

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
