### ISSUE TITLE
I use the method above, but never received a callback.

### ISSUE THREAD

**Issue by JQHee** [malcommac/SwiftLocation#143]
let x = Location.getLocation(accuracy: .room, frequency: .oneShot, timeout: 60 * 60 * 5, success: { (request, location) in
            debugLog(location)
            request.cancel()
            
        }) { (request, lastLocation, error) in
            debugLog("Location monitoring failed due to an error \(error)")
            request.cancel() // stop continous location monitoring on error
        }

question: 

iPhone 5c iOS 10.3.2
I use the method above, but never received a callback.

log:

Authorization moved from Not Determined to Not Determined
Settings 
	- Accuracy: 'Room'
	 - Frequency: 'One Shot'
	 - Activity: 'Other'
	 - Distance filter: '-1.0'
Authorization moved from Not Determined to Authorized When In Use

**Comment by vincentsaluzzo** [comment]
Up, I've exactly the same problem.

Did you use Swift 4 ? For my self, I'll use it and my first idea was probably a compatibility error but I seen your issue, and you're not mention Swift 4

**Comment by vincentsaluzzo** [comment]
Forgot my comment I've use simulator, and if we don't specify explicitly a location, there is not location update in core location framework. All is good for me right now :)

**Comment by malcommac** [comment]
thank you

**Comment by apascual** [comment]
I don't know why this is closed... I am experiencing the same issue, room & house accuracy levels always end up in timeout errors, even after long timeouts...
