### ISSUE TITLE
Pushing to AppStore, appStore says we should turn off backgroundmode and use significant but we are already

### ISSUE THREAD

**Issue by mding5692** [malcommac/SwiftLocation#144]
Hi there, thanks for providing this library.

So my issue is that Apple App Store recommends I turn off backgroundmode for location and instead use Significant Location Changes, but I checked and I am using requestLocation with significant as the frequency. And running my code requires backgroundmode or else my app crashes while on simulator.

Has anyone else faced this and am I doing something wrong?

**Comment by adenisonafifi** [comment]
I noticed that SwiftLocation assumes the location UIBackgroundModes key is set (the same problem you're describing). This is addressed this in my pull request:  https://github.com/malcommac/SwiftLocation/pull/136

I haven't heard back about the PR, but feel free to use it to get around the UIBackgroundModes issue.

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
