### ISSUE TITLE
Distance filter always set to best?

### ISSUE THREAD

**Issue by dannygrob** [malcommac/SwiftLocation#146]
You define
`var distanceFilter: CLLocationDistance? = kCLDistanceFilterNone`

And later check:

```
// the current value, we want to store it. Lower value is the setting.
if distanceFilter != nil && request.minimumDistance! < distanceFilter! {
    distanceFilter = request.minimumDistance!
}
```
This will always take the minimum distance of `kCLDistanceFilterNone`, regardless of what the user inputs, say 25 meters. Because it's initially set to none (-1) it will always be -1. Or do I misunderstand the function here?

When defining:
`var distanceFilter: CLLocationDistance? = 1000` it will accept my 25 meters

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
