### ISSUE TITLE
Region monitoring sometimes fail to intercept didEnterRegion or didExitRegion

### ISSUE THREAD

**Issue by francesco-clementi-92** [malcommac/SwiftLocation#148]
I am working on xcode 8.3.3 on a project written in Swift2.3.
I installed SwiftLocation (2.3 Branch) via Cocoapods in order to monitor region events (didEnter/didExit Region).

I had 3/4 region to monitor on average at the same time
I add them as it follows:
` do {
    let monitor = try Beacons.monitor(geographicRegion: epicenter, radius: 100, onStateDidChange: { (state) in
        state == .Entered ? self.delegate?.checkedIn(id, status: .Awake, onFinish: nil) : self.delegate?.checkedOut(id, status: .Awake, onFinish: nil)
        
   }) { (error) in
        let error = NSError(domain: “Monitor”, code: error._code, userInfo: [NSLocalizedDescriptionKey : error.description])
        self.delegate?.failedBecause(error)
    }
    
   monitor.onAuthorizationDidChange = { status in
        self.delegate?.movedTo(status)
    }
    
} catch let error {
    let error = NSError(domain: “Monitor”, code: error._code, userInfo: [NSLocalizedDescriptionKey : error as! AnyObject])
    self.delegate?.failedBecause(error)
}
 `
I have activated Background Modes and asked for Authorization and I am sure it is working in background because the app is woke up and I am able to get events even if the app has been killed.
Moreover both the gps and the internet coonection on the device are turned on. The feature seems to work well, but often the callback “onStateDidChange” of the method “Beacons.monitor(:)” doesn’t get called. It’s really weird that I have a great number of exit event, but not too many entrance.

We already tested if this situation occurs only because the device was inside the region when monitoring was added but this seems to be not the reason. How is possible to have sometimes only the exit event but not the entrance? To intercept the exit event, the system knows that the device was inside the region, but the entrance event hasn’t been triggered.
Any help on fix this or debugging it is really appreciated

**Comment by malcommac** [comment]
I'm sorry but Swift 2.3 is not supported anymore.

**Comment by otymartin** [comment]
@francesco-clementi-92 Did you ever fix this issue? What was the underlying cause?

**Comment by francesco-clementi-92** [comment]
Hi @otymartin , I'm not working anymore on that project, but at that time I didn't find a way to fix the issue.
