### ISSUE TITLE
Accuracy.Country no longer works (callback does not trigger at all)

### ISSUE THREAD

**Issue by driver733** [malcommac/SwiftLocation#15]
https://ip-api.com/json - the website that you use - is down, so it is impossible to use Accuracy.Country anymore.

**Comment by vladc** [comment]
https is not available for ip-api.com, I'm unsure why [this](https://github.com/malcommac/SwiftLocation/commit/4c23c0f258c03ecfbce22608dcef6e9117569e13#diff-df954f1c757366459bbc714d5b1da00aR541) was merged.

**Comment by driver733** [comment]
@vladc, Indeed!

**Comment by zirinisp** [comment]
problem is that callbacks never get triggered and my UI is stuck in waiting for an answer. It also does not ever time out.

**Comment by happiehappie** [comment]
Just encountered this, thanks for letting me know that I am not alone. +1

**Comment by malcommac** [comment]
no longer valid. Test 0.9.0
