### ISSUE TITLE
LastLocation bestAccurated is calculated wrongly 

### ISSUE THREAD

**Issue by iThinker** [malcommac/SwiftLocation#151]
```location.horizontalAccuracy > self.bestAccurated!.horizontalAccuracy```
is wrong comparison. The lower accuracy the better. Not vice versa.
```location.horizontalAccuracy < self.bestAccurated!.horizontalAccuracy``` is right code.
Sorry for not making PR. Do not have time at the moment.

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
