### ISSUE TITLE
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]

### ISSUE THREAD

**Issue by iDeveloperCom** [malcommac/SwiftLocation#152]
In the file LocationTracker.swift on line 931 the call 
let isAppInBackground = (UIApplication.shared.applicationState == .background && CLLocationManager.isBackgroundUpdateEnabled)

should be in Main Thread. 

Environment: iOS 11 Beta XCode Version 9.0 beta 6 (9M214v)

**Comment by malcommac** [comment]
Solved in 3.x branch.
Thanks
