### ISSUE TITLE
No such module SwiftLocation - Xcode 9

### ISSUE THREAD

**Issue by ravinleague** [malcommac/SwiftLocation#154]
Hi,

I have an issue with using SwiftLocation Pod in my recently updated Xcode9. I get a No such module error....

I've added the SwiftLocation.framework also. but it appears 'disabled' in build settings.

Any know issues with Xcode 9?

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
