### ISSUE TITLE
Build error when used with Swift 4

### ISSUE THREAD

**Issue by evermeer** [malcommac/SwiftLocation#155]

**Comment by day1-suraj** [comment]
@malcommac When would receive the update for Swift4?

**Comment by malcommac** [comment]
I'll rewrite it from the groundup; hope tu publish a first release in the second middle of October.

**Comment by Billlyevans** [comment]
i need this to work with ios11


like really need this



please

**Comment by malcommac** [comment]
In he meantime you can consider it https://github.com/intuit/LocationManager. It’s very similar.

**Comment by francodriansetti** [comment]
In meantime I've found a **solution**: Just compile SwiftLocation in Swift 3.2 and other code in Swift 4

**Comment by suraj-shetty** [comment]
@malcommac There's a pull request from @hamzaansari09 titled **Swift 4 and Xcode 9 compatible** having the required fixes. Can you verify and merge this pull request?

**Comment by hamzaansari09** [comment]
PR #156

**Comment by malcommac** [comment]
A new rewritten version for Swift 4 is available on master.
thanks
