### ISSUE TITLE
error block not entered when user presses do not allow on the message about getting user location the first time

### ISSUE THREAD

**Issue by gregoryew** [malcommac/SwiftLocation#158]
I have the following code to use SwiftLocation
    func getZipCode() {
        
        Location.getLocation(accuracy: .city, frequency: .oneShot, success: { (_, location) in
            print("A new update of location is available: \(location)")
            Location.getPlacemark(forLocation: location, success: { placemarks in
                zipCode = placemarks.first!.postalCode!
                self.setFilterDisplay()
                self.pets?.loading = true
                DownloadManager.loadPetList()
                self.setupReloadAndScroll()
                print("Found \(placemarks.first!.postalCode ?? "")")
            }) { error in
                self.askForZipCode()
                print("Cannot retrive placemark due to an error \(error)")
            }
        }) { (request, last, error) in
            request.cancel() // stop continous location monitoring on error
            print("Location monitoring failed due to an error \(error)")
            self.askForZipCode()
        }
    }

When the user downloads my app and presses do not allow the app to get the current location the error block does not execute.  When the user exits the app and reruns it the error block is entered and works correctly.  I was able to trace to the didChangeAuthorization block in SwiftLocation and got a notDetermined error back in the following method of SwiftLocation which goes to the default section.  I am at a loss as to what to do to fix it.

	@objc open func locationManager(_ manager: CLLocationManager, didChangeAuthorization status: CLAuthorizationStatus) {
		locationRequests.forEach { $0.dispatchAuthChange(self.lastStatus, status) }
		self.lastStatus = status
		
		switch status {
		case .denied, .restricted:
			let error = LocationError.authDidChange(status)
			self.pools.forEach { $0.dispatch(error: error) }
			self.updateServicesStatus()
		case .authorizedAlways, .authorizedWhenInUse:
			self.pools.forEach { $0.resumeWaitingAuth() }
			self.updateServicesStatus()
		default:
			break
		}
	}

I am using OS11 and XCode 4.   I am not sure if this is the issue.

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
