### ISSUE TITLE
get location returns wrong value

### ISSUE THREAD

**Issue by samahyousif** [malcommac/SwiftLocation#159]
Location.getLocation(accuracy: .block, frequency: .oneShot, timeout: 1*60,...)
returns wrong result
any Idea about that??

**Comment by SalAldana** [comment]
When you say wrong result what exactly is wrong and how are you determining it's wrong? For example are you using the simulator and one of the built in locations for the simulator (like Apple's headquarters) or are you using an actual device?

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
