### ISSUE TITLE
Getting background locations and oneShot locations

### ISSUE THREAD

**Issue by SalAldana** [malcommac/SwiftLocation#160]
I'm trying to get SwiftLocation setup in an existing project to replace the existing location methods but I'm having issues with both getting the background status setup and getting a oneShot location as well. In my AppDelegate I'm setting up the background task (although the isBackgroundRequest keeps coming back false) like this : 
`self.backgroundRequest = Location.getLocation(accuracy: .any, frequency: .significant, success: {(request, recentLocation) in`

And then for one screen I would like to get the most accurate location so I'm trying to call a oneShot location request like this : 
`self.oneShotRequest = Location.getLocation(accuracy: .room, frequency: .oneShot, success: {(request, location) in` but when I test on my device I don't get a callback from the oneShot request. 
 
I even tried pausing the background request before calling the oneShot request using `Location.cancel(self.backgroundRequest)` but that didn't seem to work. 

Any ideas on one, getting a one time accurate location while background/significant locations is running and two, how to make sure the task is actually running in the background.

**Comment by SalAldana** [comment]
Actually quick update, after tinkering around some more I was able to get the oneShot to work after pausing the background task, but I'm still not sure if the background task is actually running in the background. When I look at the LocationRequest source it looks like only deferred locations are capable of running in the background but the documentation says that significant frequency should be used. 

`/// `true` if request works in background app state
	public var isBackgroundRequest: Bool {
		switch self.frequency {
		case .deferredUntil(_,_,_):
			return true
		default:
			return false
		}
	}`

**Comment by samahyousif** [comment]
I've same problem

**Comment by SalAldana** [comment]
@samahyousif which problem are you having? I was able to figure it out. You need to create a variable for both the background request and the one shot request and before calling the one shot the background task needs to be paused not canceled (Location.pause(self.backgroundRequest)) and then the one shot seems to work fine. 

Also, the significant state does work in the background just the LocationRequest "isBackgroundRequest" needs to be updated to include significant as well. I've been getting background requests using it for the past couple days so it is working.

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.

See the README for info about using significant location monitoring in background.
Thanks
