### ISSUE TITLE
Support for region monitoring support (exit/enter)

### ISSUE THREAD

**Issue by malcommac** [malcommac/SwiftLocation#162]
Support region monitoring in background and foreground.

**Comment by bmt22033** [comment]
Is region monitoring still slated for 3.1.0?

**Comment by wolfAle** [comment]
Hi Daniele :-)

this is something I'm really looking forward to see implemented, if you needed any help on this side please raise your hand, I might be able to find some time to inspect it.

Thanks,
Alessandro

**Comment by malcommac** [comment]
Added in 5.0
