### ISSUE TITLE
Filter by distance/interval in continuous location update

### ISSUE THREAD

**Issue by malcommac** [malcommac/SwiftLocation#163]
Add distance/interval filters when monitoring location updates continuously.

**Comment by ghost** [comment]
This feature was available in old version. I would soon need it to go live.
Could you give any prediction when it's going to be implemented?
And what about the activityTypes? It's also missing now.

**Comment by radvansky-tomas** [comment]
Any update on this ? Specially intervals for background task. For example to be able to setup, that location should be read every 20s

**Comment by colorscale** [comment]
Need it too. Is there any possibility to timeout the continuous location update? Best wishes.

**Comment by GhaisB** [comment]
Same here, it would be great to have this implemented ! 
Best wishes !
