### ISSUE TITLE
Missing argument for parameter #1 in call

### ISSUE THREAD

**Issue by a-v-ebrahimi** [malcommac/SwiftLocation#168]
When I try to build latest pod, I receive this error :

**Missing argument for parameter #1 in call**

LocationTracker.swift (line 564):

![image](https://user-images.githubusercontent.com/179375/32843613-6fbc69ea-ca35-11e7-800f-33b67be49034.png)

**Comment by Strobocop** [comment]
@ControlAdad I noticed the same issue. Looks like there is a fixed version in this fork (https://github.com/hamzaansari09/SwiftLocation) that will at least temporarily work for you until there is a fix pulled into the main repo.

**Comment by Eric0625** [comment]
It's because of the syntax changing in Swift 4, so locate it in RegionRequest.swift(line 90) and change the declaration to:
`public var onStartMonitoring: (() -> (Void))? = nil`

**Comment by malcommac** [comment]
Region monitor is currently not available anymore.
I'll plan to add it again with a new rewritten version on 3.5 branch.
