### ISSUE TITLE
Expose authorizationStatus in Locator

### ISSUE THREAD

**Issue by ghost** [malcommac/SwiftLocation#176]
```swift
if CLLocationManager.authorizationStatus() == .denied {
}
```

怎么没有封装系统的这个属性，是我没找到吗？如果有了就方便很多，不用每次 `import SwiftLocation` 同时 `import CoreLocation` 了。

**Comment by ghost** [comment]
好像找到了，在请求回调的 Error 里面。

**Comment by malcommac** [comment]
Hi,
Just added `authorizationStatus` property in `Locator` so you can call directly `Locator. authorizationStatus` to get the current status of the authorization.
