### ISSUE TITLE
Probably doing something wrong, but cannot get it to work...?

### ISSUE THREAD

**Issue by benvigier** [malcommac/SwiftLocation#177]
This framework seems awesome, but unfortunately I cannot get any of the examples provided in the documentation to build in my test app. Xcode does not find "Locator" nor most of the other variables and functions described. I even searched the swift files for some of the calls in the examples and could not find them.

My configuration:
Xcode 9.1
Swift 4
Successfully installed SwiftLocation via Cocoapod and imported the framework in my app.

I did manage to get the current location by using Location.getLocation() instead of using Locator, and then assumed that the framework no longer matches the documentation. I searched for some examples showing how to use it on Google but could not find any.

All this said, I am a beginner swift developer and am probably missing something. I'd much appreciate if someone could point me in the right direction on how to use this framework as per the documentation (or point me to some updated documentation). 

Thanks a ton

**Comment by imfeemily** [comment]
I think you forgot to set the version name in Pod file like this -> 'SwiftLocation', '~> 3.1.0' 

Hope it might be helped you.
