### ISSUE TITLE
currentPosition with .room or .house accuracy always timesout and location is nil

### ISSUE THREAD

**Issue by josselin-oudry** [malcommac/SwiftLocation#179]
Hi there,

Thanks for the great library. I've been using it for just an hour so I hope I'm doing something wrong... 

Context: I'm testing inside a building and using the latest and greatest 3.1.0 version.

If I make such a call with accuracy set to .room or .house, the execution takes 60 seconds and then .onFail is called, which is fine, but then within .onFail, location is always nil. 

        SwiftLocation.Locator.currentPosition(
            accuracy: .house,
            timeout: Timeout.delayed(60.0),
            onSuccess: { cllocation in
                
                log.debug("Location:\(cllocation.debugDescription)")
            },
            onFail: { locationError, cllocation in
                
                log.debug("Failed to get location: \(locationError). Location:\(cllocation.debugDescription)")
            }
        )

I expected it to have some value with an horizontalAccuracy of let's say 65 meter. Indeed if I set the accuracy to .block, onSuccess is called almost immediately with an horizontalAccuracy of 65 meter.

**Comment by musbaalbaki** [comment]
I am facing the same issue

**Comment by jonasbark** [comment]
same here, although it only happens on iPhone 7

**Comment by josselin-oudry** [comment]
My test was on an iPhone 6 with iOS11.

**Comment by malcommac** [comment]
Cannot reproduce this bug. With this exact code it works; are you sure you are able to get this accuracy? (you are inside a building etc.).
Also try the new 3.2.0 update.

**Comment by josselin-oudry** [comment]
Thanks a lot for your reply. I'm on the latest version of SwiftLocation.

I'm actually still experiencing the behaviour described in the initial post. Indeed I'm inside a building and I understand that it's quite difficult for the Location Manager to retrieve such an accuracy as .room or .house, but I still expected the cllocation, in the fail block, not to be nil and have a value of whatever horizontalAccuracy.
