### ISSUE TITLE
Runtime error - EXC_BAD_ACCESS with Mapbox-iOS-SDK Info.plist change

### ISSUE THREAD

**Issue by jasonicarter** [malcommac/SwiftLocation#18]
Ran across what seems like a conflict in Info.plist when using Cocoapods - SwiftLocation and Mapbox-iOS-SDK. 

``` javascript
platform :ios, '8.0'
use_frameworks!

target 'swiftLocationTest' do
    pod 'SwiftLocation', '~> 0.2'
    pod 'Mapbox-iOS-SDK', '~> 3.0'
end
```

**Recreate (in simulator)**
- Create new project
- Create pod and add SwiftLocation
- Update pod, build+run everything works
- Add Mapbox-iOS-SDK
- Update pod, build+run everything works
- Setup Mapbox
  - add mapbox provided Settings.bundle file and update Info.plist with access token
- Update pod, build+run error (see below)

<img width="1020" alt="screen shot 2015-12-02 at 8 56 59 pm" src="https://cloud.githubusercontent.com/assets/5205478/11550122/801e6cbc-993a-11e5-9e74-504800788840.png">

**Believed cause**
Mapbox access key name conflict with SwiftLocation for Info.plist ( Key: MGLMapboxAccessToken )

Did some messing around and my test app works when the individual pods are installed (comment out SwiftLocation or Mapbox) and with different pods installed (SwiftLocation + another pod besides Mapbox). But once you have SwiftLocation and Mapbox together and add the mapbox plist edits, it breaks. 

You can edit the plist with any variation of the required Key ( MGLMapboxAccessT or MGLMapboxToken or etc etc ) and build+run works. So I'm guessing some type of naming conflict somewhere and out of the two projects I'm betting you would care more to try to fix it.

<img width="1275" alt="screen shot 2015-12-02 at 9 19 12 pm" src="https://cloud.githubusercontent.com/assets/5205478/11550136/a3dd15ea-993a-11e5-87a3-c868ec32aeaa.png">

**Comment by misuqian** [comment]
I copy SwiftLocation.swift directly to project and install MapBox by pod.
You can try this

**Comment by jasonicarter** [comment]
Thanks for the suggestion. 
I wanted to use pod for all third parties, so looked into it a bit more and figured out instead of updating the plist I can do it in the AppDelegate.swift file. Works.

``` javascript
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
...
MGLAccountManager.setAccessToken(token)
return true
}
```

thanks
