### ISSUE TITLE
Question: how to clear Events.authorizationsStatus array

### ISSUE THREAD

**Issue by yodasl** [malcommac/SwiftLocation#180]
First, thanks for open sourcing the framework. Really appreciate it.
Question: using the framework, I am registering my callback/block for status change with:
```
Locator.events.listen { newStatus in
```
so far so good, and I am getting the proper callback when the status change... Now how do I stop listening for the event ? I don't see anyway to unregister my block.

**Comment by malcommac** [comment]
Now you are able to remove a specific listener becuause the `listen()` function return a `TokenID` (an `UInt64`) you can use as parameter for `Locator.events.remove()` to remove your handler.
Thanks for reporting.
