### ISSUE TITLE
Support Apps that only need "WhenInUse" authorization Level

### ISSUE THREAD

**Issue by ahalls** [malcommac/SwiftLocation#181]
I think you have misunderstood the limitation imposed in iOS 11 in this area.  It is not that Always is required, it's that WhenInUse is required.   Apps can no longer offer Always as the only option. If the app developer wants to use background tracking (Always) they must also offer WhenInUse. 

Kuba Suder's post [Changes to location tracking in iOS 11](https://mackuba.eu/2017/07/13/changes-to-location-tracking-in-ios-11/) covers it in detail.

His quote from Brad Jensen's WWDC talk, explains Apple decision that forcing the user to give the app “Always” location access is a bad user experience:

> Now, a second reason we think that many developers choose to require Always authorization is they’re simply trying to give their users the best possible experience (…) but this makes for a very poor user experience for the users that don’t wish to grant the app Always authorization. They are forced to choose between granting the app Always, which is more than they would like in this example, or granting it Never, which means they don’t get to benefit from any of the app’s location-based features. And their final option is to grant it Always and then revoke that authorization after they’re done using the app. In any case, the user is not having a great time with this app.

With SwiftLocation 3.1.0. a fatal error is issued when the app requests WhenInUse access only.

Error Message:
`fatalError("To` use location services in iOS 11+, your Info.plist must provide a value for NSLocationAlwaysAndWhenInUseUsageDescription.") `
File: shared.swift, line: 252

It should accept this configuration.

**Comment by J7mbo** [comment]
Any idea if this will be merged any time soon?

**Comment by malcommac** [comment]
Fixed in 3.2.0. Thanks for reporting.

**Comment by J7mbo** [comment]
Thanks a lot @malcommac!
