### ISSUE TITLE
Ambiguous reference to member 'currentPosition(accuracy:timeout:onSuccess:onFail:)'

### ISSUE THREAD

**Issue by peter369** [malcommac/SwiftLocation#182]
I get error "Ambiguous reference to member 'currentPosition(accuracy:timeout:onSuccess:onFail:)' " when trying to use:

```swift
Locator.currentPosition(accuracy: .city).onSuccess { location in
            print("Location found: \(location)")
            }.onFailure { err, last in
                print("Failed to get location: \(err)")
        }
```

**Comment by seangeiger** [comment]
Changing the closure to something like this worked for me:

        SwiftLocation.Locator.currentPosition(accuracy: .city, timeout: nil, onSuccess: { location in
            print("Location found: \(location)")
            }) { (err, last) -> (Void) in
                print("Failed to get location: \(err)")
        }
