### ISSUE TITLE
SwiftyJson image not found

### ISSUE THREAD

**Issue by DrAma999** [malcommac/SwiftLocation#185]
I've recently update the library using `Carthage`, now when I launch my application I receive this error:
```
dyld: Library not loaded: @rpath/SwiftyJSON.framework/SwiftyJSON
  Referenced from: /Users/xxx/Library/Developer/CoreSimulator/Devices/9FF7FB79-307C-4A3D-9AEC-EBBCCAEBD477/data/Containers/Bundle/Application/A5B370B3-7CDC-4C13-A616-D20CA6B9C944/yyy.app/Frameworks/SwiftLocation.framework/SwiftLocation
  Reason: image not found
```
It seems that there is a dependency not resolved while building the SwiftLocation framework.
Of course if I add it in my Carthage file everything works.

**Comment by federicopolesello** [comment]
+1

**Comment by malcommac** [comment]
If you are using Carthage you also need to include SwiftyJSON in your Cartfile; this because Carthage does not support dependency support in libraries yet.

```
github "SwiftyJSON/SwiftyJSON"
```

Added in documentation.
