### ISSUE TITLE
Thread 1: signal SIGABRT - Possible reason for crash?

### ISSUE THREAD

**Issue by Lennartbrugger** [malcommac/SwiftLocation#195]
![img](https://user-images.githubusercontent.com/35659043/35454175-46d9851e-02cd-11e8-8333-1ee58b937d14.png)

I don't know what I am doing wrong. I have added the framework to my project and everything seems to work fine but running the application will crash my iOS device in every case.

Even if I just call `print(Locator.authorizationStatus)` I got a crash message named **Thread 1: signal SIGABRT**.

What could be a possible reason for this behavior? 

import SwiftLocation
import CoreLocation

```
public class myclass {
    public init() {
    }
    public go() {
      print(Locator.authorizationStatus) // ----> crash
    }
}

```

**Comment by malcommac** [comment]
Can you say more about the crash? Stacktrace?
