### ISSUE TITLE
Locator.currentPosition does not return, but CLLocationManager is able to determine the location changes

### ISSUE THREAD

**Issue by bogdan-razvan** [malcommac/SwiftLocation#198]
It sometimes happens that `Locator.currentPosition(accuracy: .block, onSuccess: { (location) -> (Void) in ..... }` does not return the location, even if waiting for some minutes. 

Firstly I thought it was a problem with my device, I've restarted it, reinstalled the app, disabled and enabled location services, but I couldn't get the location method to return. I've tried the same method call after adding a CLLocationManager in the same ViewController, and it displays the device's current location immediately, thus leaving me to think the problem lies in the pod.

Did anyone also stumble upon this odd behavior?

**Comment by marwan87** [comment]
Im getting the same behaviour, if you go to apple maps or something it seems to then kick the app into action

**Comment by bogdan-razvan** [comment]
@marwan87 going to apple maps didn't kick the app into action for me, thinking of replacing this pod.

**Comment by marwan87** [comment]
I ended up replacing it, and on continuous position seems to work

**Comment by malcommac** [comment]
Are you sure you are not requesting too much accuracy for your position? (ie. inside a building).
If location accuracy cannot be achieved in the timeout interval requests will fail by returning the error and last retrived location.

**Comment by pmarrufo** [comment]
I'm having the same issue. I have tried .city of accuracy or .any. And the app gets stuck

**Comment by alkanyunus** [comment]
> I'm having the same issue. I have tried .city of accuracy or .any. And the app gets stuck

Me too. I'was thinking my server cannot respond, but I did deep debugging and I found this problem.

> I ended up replacing it, and on continuous position seems to work

Do you think this works? So I'll change my currentPosition method with this!

**Comment by anirudhamahale** [comment]
You can use the `currentPosition(accuracy:timeout:onSuccess:onFail:)` function.

**Comment by zenghaojim33** [comment]
Similar problem here, using `.block` accuracy works well (still there is at least 100m away from the real location) but using `.house` and  `room` never get successful response. Meanwhile `mapView.showsUserLocation` works perfectly.  Anyone know how to solve this?
