### ISSUE TITLE
Unable to build project example

### ISSUE THREAD

**Issue by walsht** [malcommac/SwiftLocation#2]
Unable to build project example...

**Comment by malcommac** [comment]
Are you using it with Swift 1.2?

**Comment by walsht** [comment]
I thought I tried both, but probably. Are you going to convert?

**Comment by malcommac** [comment]
With Swift 1.2 and XCode 6.4 it works fine.
Yeah, I'm planning to move from Swift 1.2 to Swift 2 in two weeks as I've enough spare time.
