### ISSUE TITLE
Remove SwiftyJSON dependancy from 3.x branch

### ISSUE THREAD

**Issue by jyounus** [malcommac/SwiftLocation#205]
Hey there,

It would be great if SwiftyJSON could be an optional dependancy for SwiftLocation.

As far as I can tell, SwiftyJSON is used mainly for IP look ups and geocoding, in other words only if you use any of the thirdparty services to obtain location information.

I just need to simply fetch the user's current location, so I don't need the additional functionality (for any of the thirdparty related services). It would be great if in those simple scenarios, it wouldn't download SwiftyJSON.

I'm using Cocoapods, so splitting it up into something like this would be perfect imo:
```
pod 'SwiftLocation'
pod 'SwiftLocation/Thirdparty'
```

Maybe even consider removing SwiftyJSON as a dependancy and just use Swift 4's Codable protocol?

(This obviously isn't an issue, but more of a suggestion to try and keep my podfile to a minimum and only with code that is needed in my project.) 😄

**Comment by mapo80** [comment]
+1

**Comment by eitanaviv** [comment]
+1

**Comment by soyjimmysaenz** [comment]
+1

**Comment by wpompeigaiago** [comment]
Hi @malcommac :  I'd like to know about the 3.3.0 release time (as we're interested in removing the SwiftyJSON alpha dependencies).

Thanks!
William Pompei
