### ISSUE TITLE
[Build Error] Cannot load underlying module for 'SwiftyJSON'

### ISSUE THREAD

**Issue by iad24** [malcommac/SwiftLocation#208]
1. I downloaded everything as zip
2. Go to folder in terminal, run 'pod install'
3. Open the workspace
4. Clean
5. Build

![screen shot 2018-04-11 at 1 23 01 pm](https://user-images.githubusercontent.com/15226261/38597704-d281de1a-3d8b-11e8-8c4c-677cf5953554.png)

**Comment by HongChow** [comment]
the same as mine

**Comment by ghost** [comment]
Same here! What do we do?

**Comment by islamnurdin** [comment]
Did you find something?

**Comment by grehce** [comment]
Build the project again. Seems to be an xcode bug.
https://stackoverflow.com/questions/32673866/cocoapods-cannot-load-underlying-module-for-x
