### ISSUE TITLE
Massive bug: pod checks the info.plist file for wrong permission key when requesting "when-in-use" location access in iOS11

### ISSUE THREAD

**Issue by bogdan-razvan** [malcommac/SwiftLocation#215]
SwiftLocation checks the info.plist file for the `NSLocationAlwaysAndWhenInUseUsageDescription` key when requesting `whenInUse` permission. It fails all the time, because the app's `info.plist` should not contain that kind of key in its `info.plist` for requesting `whenInUse` authorization, instead `NSLocationWhenInUseUsageDescription` should be searched for.

This all happens inside the "Shared" swift file, line 274

Reference: https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services/requesting_when_in_use_authorization

**Comment by malcommac** [comment]
Fixed in 3.x branch. Thanks
