### ISSUE TITLE
subscribePosition not retriggered when internet connection goes down temporarily

### ISSUE THREAD

**Issue by sindunarasimhan** [malcommac/SwiftLocation#217]
I am using Locator.subscribePosition to track location updates in my app. This works great even in background, however it does not seem to be able to recover when the network is spotty / temporarily unavailable. 

I tested this by using this sample application and tracking logs in Sentry. The way to reproduce the issue is by backgrounding the app, turning off network, wait for a few seconds and turn it back on. Here's the link to the repo https://github.com/sindunarasimhan/BackgroundLocator

Do let me know if you have a chance to evaluate this. I am working on a location based notification app, and expect the user to be in spotty network zones.

**Comment by umwelt** [comment]
Did you have a chance to evaluate this? If you point me to some direction I can take a look at it
