### ISSUE TITLE
No such module 'SwiftyJSON'

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [malcommac/SwiftLocation#219]
Hi,

I cloned the latest source of the library and ran `pod install`. But when I try to run the Test application I get the compile error **No such module 'SwiftyJSON'**. I also get the below warning on Xcode.

> Target 'Pods-SwiftLocation-iOS' of project 'Pods' was rejected as an implicit dependency for 'Pods_SwiftLocation_iOS.framework' because its architectures 'armv7' didn't contain all required architectures 'armv7 arm64'

I'm using Xcode 9.4 and CocoaPods v1.4.0.

**Comment by JoseSanchezMirandaRos** [comment]
Same here...

**Comment by jigar007** [comment]
same here

**Comment by denis631** [comment]
Same here

**Comment by malcommac** [comment]
I'm working to remove SwiftyJSON. Follow #205
