### ISSUE TITLE
Significant Location : Only the first update is received

### ISSUE THREAD

**Issue by vicorente** [malcommac/SwiftLocation#22]
Hi, I've checked in your code that when you call:

``` swift
completeRequest(request: SwiftLocationRequest!, object: AnyObject?, error: NSError?)
```

and then you check the request type:

``` swift
if cRequest.isCancelled == true || cRequest.type != RequestType.ContinuousLocationUpdate) {
    self.requests.removeAtIndex(idx)
}
```

This is removing any requests different from `ContinuousLocationUpdate`, including `ContinuousSignificantLocation`. This causes that only the first location update is processed in the callback when you use significant location method. The solution is that simple: 

``` swift
if cRequest.isCancelled == true || (cRequest.type != RequestType.ContinuousLocationUpdate && cRequest.type != RequestType.ContinuousSignificantLocation)  {
    self.requests.removeAtIndex(idx)
}
```

Thanks for your time. 
Great job!

**Comment by efremidze** [comment]
:+1:

**Comment by malcommac** [comment]
Fixed
