### ISSUE TITLE
Exposed showsBackgroundLocationIndicator (iOS 11 only)

### ISSUE THREAD

**Issue by torok-zoltan** [malcommac/SwiftLocation#220]
Hello

In iOS 11 the Location Manager received a new flag, showsBackgroundLocationIndicator:
"This property affects only apps that received always authorization. When such an app moves to the background, the system uses this property to determine whether to change the status bar appearance to indicate that location services are in use. Displaying a modified status bar gives the user a quick way to return to your app. The default value of this property is false.
For apps with when-in-use authorization, the system always changes the status bar appearance when the app uses location services in the background."

Is there a way to access this property in the current implementation so I can enable the status bar appearance modification?

**Comment by malcommac** [comment]
Exposed `Locator. showsBackgroundLocationIndicator` (iOS 11).
Thanks.
