### ISSUE TITLE
SwiftyJSON 4.1.0

### ISSUE THREAD

**Issue by LittlePhoenix8** [malcommac/SwiftLocation#221]
Hi!

I'm using the latest version of SwiftyJSON on my project and when I try to add SwiftLocation pod I got this error:

`[!] CocoaPods could not find compatible versions for pod "SwiftyJSON":
  In snapshot (Podfile.lock):
    SwiftyJSON (= 4.1.0)

  In Podfile:
    SwiftLocation (~> 3.2.3) was resolved to 3.2.3, which depends on
      SwiftyJSON (~> 4.0.0-alpha.1)

    SwiftyJSON`

I changed my podfile to used the 4.0.0-alpha version and it worked, but maybe you could switch to the latest version of SwiftyJSON on the next update

**Comment by malcommac** [comment]
I'm working to remove this dependancy.
Follow #205
