### ISSUE TITLE
Required accuracy/time stale levels for room/house were adjusted

### ISSUE THREAD

**Issue by pbeneteau** [malcommac/SwiftLocation#227]
Hi,

I can't get the current position because the pod doesn't work with accuracy city and room. Here is my simple code:

```swift
func getCurrentLocation() {
        
        // Manually request given authorization
        Locator.requestAuthorizationIfNeeded(.always)
        // determine the best authorization mode based upon Info.plist file
        Locator.requestAuthorizationIfNeeded()
        
        Locator.currentPosition(accuracy: .room, onSuccess: { location in
            print("Found location: \(location)")
        }) { err, _ in
            print("\(err)")
        }
    }
```

It doesn't work: nothing happens, and no error returned. Even after 5min.

**Comment by malcommac** [comment]
Hi, there is not any bug, for `room` level the level of accuracy must be 5 meters which is too high probability (you must be outside a building for sure). However I've made an adjustment by relaxing both the constraints to `10 meters` for `room` and `15 meters` for `house`.
