### ISSUE TITLE
Fixed an issue which prevents reporting the last found location when a location discovery fails due to timeout

### ISSUE THREAD

**Issue by dev4jam** [malcommac/SwiftLocation#229]
If location discovery fails by timeout the handler doesn't receive the last available location. I see in the code that this happens because it doesn't satisfy accuracy constraint. But in error handler, it might be useful to provide the last discovered location.

**Comment by malcommac** [comment]
Absolutely true, I've integrated your change in develop branch, ready for 3.3.0. Thank you for your help.
