### ISSUE TITLE
SwiftLocation.shared.currentLocation returns CLLocation

### ISSUE THREAD

**Issue by coryhymel** [malcommac/SwiftLocation#23]
It seems that `SwiftLocation.shared.currentLocation` returns a `CLLocation` object and not a `CLPlacemark` object as the documentation states.

**Comment by arjunmayilvaganan** [comment]
+1
Swift Newbie here. Spent minutes trying to figure how to extract the coordinates from the `CLPlacemark` object. Used `.dynamicType` and realised it was `CLLocation`.

**Comment by malcommac** [comment]
Fixed
