### ISSUE TITLE
Support for ipStack (replacing freeGeoIP)

### ISSUE THREAD

**Issue by malcommac** [malcommac/SwiftLocation#235]
FreeGeoIP became IPStack and require a free (at minimum) API key setup.
More info can be [found here](
https://github.com/apilayer/freegeoip#required-changes-to-legacy-integrations-freegeoipnetjsonxmll).
We should support it and remove the old `.freeGeoIP` enum.

**Comment by raelg** [comment]
Any chance of merging this to master soon, and releasing to CocoaPods? 🙏

**Comment by OlivierVoyer** [comment]
It would be great to update the README file with the required ATS setup too. Thanks
