### ISSUE TITLE
Autocomplete request's reference is not strongly retained

### ISSUE THREAD

**Issue by malcommac** [malcommac/SwiftLocation#236]
Autocompletes request is not strongly retained during the call and if user from outside the lib does not keep it alive requests itself "disappear".
We should add a strong reference inside the requests list as like happens for other requests.

**Comment by obianachebe** [comment]
@malcommac have you found a workaround for this? When I call `Locator.autoCompletePlaces` in my viewController my success and failure callbacks never get called. The cause seems to be because `onReceiveResponse` never gets called in `JSONOperation` because `self` is nil
