### ISSUE TITLE
Continuous location monitoring not working as expected. 

### ISSUE THREAD

**Issue by razvandub** [malcommac/SwiftLocation#24]
SwiftLocation.shared.continuousLocation(Accuracy.Room ...) rarely calls the onSuccess closure. App will be suspended after a while. Tested with iOS 8.3.

**Comment by spamkiller** [comment]
SwiftLocation.shared.continuousLocation(Accuracy.Room ...) never calls the onSuccess closure. Tested with iOS 9.2.1

**Comment by malcommac** [comment]
Fixed in 0.9.0. Thank you
