### ISSUE TITLE
Automatically pausing location updates in background

### ISSUE THREAD

**Issue by torok-zoltan** [malcommac/SwiftLocation#243]
There is an issue after a while in the background the OS might pause the location updates. This is a feature of the location manager controlled by pausesLocationUpdatesAutomatically. By default this is true. Is there a way to turn this off or could you expose this setting to the locator?

https://developer.apple.com/documentation/corelocation/cllocationmanager/1620553-pauseslocationupdatesautomatical

**Comment by OlivierVoyer** [comment]
Suggestion in Locator.swift

```swift
public var pausesLocationUpdatesAutomatically: Bool {
  set { self.manager.pausesLocationUpdatesAutomatically = newValue }
  get { return self.manager.pausesLocationUpdatesAutomatically }
}
```

**Comment by malcommac** [comment]
It's available in 4.x branch. thanks
