### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by wolfAle** [malcommac/SwiftLocation#246]
Hi,

is this repos still maintained? 
I can see a few issues open and a few PRs waiting for merge, last commits were on March.
I hope to see a positive answer. :-)

Thanks,
Alessandro

**Comment by klische** [comment]
I think it's safe to assume that it is abandoned, as this comment has not received a reply in a month. And it's been 11 months since the last commit.

**Comment by wolfAle** [comment]
Yeah, I got to the same conclusion. It's a pity tho, the library it's quite useful but it's lacking a few things that would really help (and I think there are PRs for these).
I'm considering to fork it..

**Comment by malcommac** [comment]
Hi, library was not abandoned. I plan to make some heavy interventions like removing the SwiftyJSON dependency (for Codable) but at this time I need to follow two other big updates. I plan to come back here later at the end of March but in meantime if you want to propose PRs I will be more than happy to discuss it.

**Comment by wolfAle** [comment]
Ah, I'm glad to hear that :-)
There are a few PRs awaiting for review that would be good to have merged, and I'll come up with another one that I think would add some value. 

Thanks!
