### ISSUE TITLE
Switch must be exhaustive in Frequency.swift class

### ISSUE THREAD

**Issue by bhanushalilinesh** [malcommac/SwiftLocation#247]
After installing the pods getting the below error in following files 

Switch must be exhaustive in Frequency.swift class

`import Foundation
import MapKit
import CoreLocation

// MARK: - Extension to CLActivityType

extension CLActivityType: CustomStringConvertible {
	
	public var description: String {
		switch self {
		case .automotiveNavigation:	return "Automotive Navigation"
		case .fitness:				return "Fitness"
		case .other:				return "Other"
		case .otherNavigation:		return "Navigation"
		}
	}
}`

and  Missing argument for parameter #1 in call in LocationTracker.swift file

`//MARK: CLLocationManager Region Monitoring Delegate
	
	public func locationManager(_ manager: CLLocationManager, didStartMonitoringFor region: CLRegion) {
		let region = self.regionRequests.filter { $0.region == region }.first
		region?.onStartMonitoring?()
	}`

**Comment by T-Coded** [comment]
Running into the same problem

Edit: @bhanushalilinesh I updated the pod to the latest release and it's building fine for me now

**Comment by malcommac** [comment]
Fixed in 4.x
