### ISSUE TITLE
Does not stop location subscription

### ISSUE THREAD

**Issue by IMDGhanshyam** [malcommac/SwiftLocation#249]
```swift
self.subscribRequest = Locator.subscribePosition(accuracy: .city, onUpdate: {[unowned self] (location) -> (Void) in
            print("Locator.subscribePosition")
            Locator.stopRequest(self.subscribRequest)
            self.subscribRequest.stop()
        }) { [unowned self](error, location) -> (Void) in
            print("Locator.subscribePosition with error")
            Locator.stopRequest(self.subscribRequest)
            self.subscribRequest.stop()
        }
```

Output:

```
Locator.subscribePosition
Locator.subscribePosition
Locator.subscribePosition
Locator.subscribePosition
Locator.subscribePosition
Locator.subscribePosition
Locator.subscribePosition
Locator.subscribePosition
Locator.subscribePosition
Locator.subscribePosition
Locator.subscribePosition
Locator.subscribePosition
Locator.subscribePosition
```

**Comment by OlivierVoyer** [comment]
I found the issue.
The request removal function is not called so the full request list is not checked again to see if we can stop completely the location updates. Please see my fix in LocationRequest.swift

	private func stopLocationRequest(_ request: LocationRequest?) -> Bool {
		guard let r = request else { return false }
		
		if r.isRecurring { // Recurring requests can only be canceled
			r.timeout?.abort()
			/// My Fix: We need to trigger removeLocationRequest extra code to see if location services can be stopped if not needed anymore
			// self.locationRequests.remove(r)
			self.removeLocationRequest(r) // remove from queue
		} else {
			r.timeout?.forceTimeout() // force timeout
			self.completeLocationRequest(r) // complete request
		}
		return true
	}

**Comment by malcommac** [comment]
Sorry I can't support old versions anymore. Switch to the latest major it should work fine.
