### ISSUE TITLE
Swift 5 support?

### ISSUE THREAD

**Issue by IceFloe** [malcommac/SwiftLocation#250]
Hi, will you add swift 5 support and remove all those warnings?

**Comment by fahlout** [comment]
+1

**Comment by malcommac** [comment]
I'm working on 4.0.0. See the 4.0.0 branch; it should ready in two weeks.
https://github.com/malcommac/SwiftLocation/tree/release/4.0.0

**Comment by malcommac** [comment]
SwiftLocation 4.0.0 was just released on master branch. Thanks for the patience.

**Comment by saroar** [comment]
did you use it and check it?

http://prntscr.com/nrt69h
after 
```
extension CLActivityType: CustomStringConvertible {
	
	public var description: String {
		switch self {
		case .automotiveNavigation:	return "Automotive Navigation"
		case .fitness:				return "Fitness"
		case .other:				return "Other"
		case .otherNavigation:		return "Navigation"
        case .airborne:
            <#code#>
        }
	}
}
```
