### ISSUE TITLE
Accuracy with WiFi capable only device

### ISSUE THREAD

**Issue by martheli** [malcommac/SwiftLocation#253]
Does this framework only support continuous location tracking via GPS now? The previous version allowed you to subscribe to get continuous coordinates on a wi-fi only device. It seems like the only options now are locateFromGPS() or locateFromIP. If I try to use the locateFromGPS() function on a wi-fi only device, nothing happens...I don't even get an error unless I turn the accuracy down to neighborhood or bigger.

**Comment by malcommac** [comment]
It still works even with WiFi because it uses the `CLLocationManager` and the source of data (gps/wifi) is completely transparent to the system.
I suppose you can't get more accuracy than the one you get because WiFi can't access to the same resolution of a GPS capable device.
