### ISSUE TITLE
Authorization not asked in case of `.significant` subscription

### ISSUE THREAD

**Issue by jeden** [malcommac/SwiftLocation#254]
If I call `locateFromGPS()` with `.significant` subscription, it doesn't ask for authorization, whereas in the case of `.continous` and `.oneShot` it does. 

It looks like a bug, I can fix it myself, but before trying, I'd like to know if that's the intended behavior.

**Comment by malcommac** [comment]
I think it’s actually a bug. You can make a PR, I’ll review it next Tue when I’ll back to office. Thanks!

**Comment by malcommac** [comment]
Fixed in 4.0.1

**Comment by jeden** [comment]
Sorry been with my head elsewhere in the latest days, and I couldn't work
on it, but I'm glad you fixed it so quickly.

Grazie 1000
Antonio
