### ISSUE TITLE
[4.0.1] Publicize completeAllLocationRequest method in LocationManager

### ISSUE THREAD

**Issue by ShadyElyaski** [malcommac/SwiftLocation#257]
I'm upgrading to 4.0.1, it would be great to make `completeAllLocationRequest` method public.
This will allow callers who create location requests be sure that there's no outstanding requests before creating a new one.
Also this will mimic the old method

> Locator.completeAllLocationRequests()

**Comment by malcommac** [comment]
Method is now public again since 4.0.2. Thanks.

**Comment by ShadyElyaski** [comment]
Thanks for the quick turnaround @malcommac
