### ISSUE TITLE
cancelRequest never returns true

### ISSUE THREAD

**Issue by spamkiller** [malcommac/SwiftLocation#26]
public func cancelRequest(identifier: Int) -> Bool 
{
    if let request = request(identifier) as SwiftLocationRequest! {
        request.markAsCancelled(nil)
        return true // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< insert this line
    }
    return false
}

**Comment by malcommac** [comment]
Fixed in 0.9.0. Thank you
