### ISSUE TITLE
SPM: Swift Package Manager compatibility with Xcode 11

### ISSUE THREAD

**Issue by arsonik** [malcommac/SwiftLocation#261]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/1333734/58932598-a4a0ed00-8764-11e9-93a1-c4bfa7590bab.png">

Source files for target SwiftLocation should be located under 'Sources/SwiftLocation', or a custom sources path can be set with the 'path' property in Package.swift

**Comment by joshuarcher** [comment]
+1

**Comment by malcommac** [comment]
Fixed. Thanks.
