### ISSUE TITLE
addressDictionary not available in the result in the locateFromCoordinates method using google

### ISSUE THREAD

**Issue by twelvedremers** [malcommac/SwiftLocation#262]
Hi, one weird thing I saw in the latest version of the library, was that in the place model that brings the `findFromCoordinates()` response, it was not bringing the original json when using the Google service, only the data already processed, this is a problem in case you need the place_id, looking at the code you see that the addressDictionary field is only initialized when using the apple service, but not in the other two services.

**Comment by malcommac** [comment]
Now identifier of the place is parsed in `identifier` property when available.
You can still access to the raw JSON parsed from thirdy party services via `rawData` property of the single `Place` instance.
