### ISSUE TITLE
'GeocoderRequest.Options' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by erpankajpatel** [malcommac/SwiftLocation#263]
![Screenshot 2019-08-06 at 12 40 20 PM](https://user-images.githubusercontent.com/50038197/62518574-854b3c80-b847-11e9-8276-83d66892753d.png)
here I am not able to access 'GeocoderRequest.Options', I had added a core location framework and all, it's not working with the latest version. I had the same as like given example. 
Please help me with this.

**Comment by syedrazackimran** [comment]
<img width="1956" alt="Screen Shot 2019-08-16 at 10 16 03 AM" src="https://user-images.githubusercontent.com/15051045/63141160-e379db80-c00e-11e9-8a6b-0a056b812635.png">

@erpankajpatel 

I'm also getting the same error, I follow as per demo. Kindly do needfully

**Comment by erpankajpatel** [comment]
> <img alt="Screen Shot 2019-08-16 at 10 16 03 AM" width="1956" src="https://user-images.githubusercontent.com/15051045/63141160-e379db80-c00e-11e9-8a6b-0a056b812635.png">
> 
> @erpankajpatel
> 
> I'm also getting the same error, I follow as per demo. Kindly do needfully

I have resolved this by my self with an edit in pods 

```swift
class Options {
         /// Additional custom paramters. It may override default service params
        public var params = [String: String]()
        
        /// Result's locale, by defualt is not set.
        ///
        /// Apple Service:
        /// The locale to use when returning the address information. You might specify a value for this parameter
        /// when you want the address returned in a locale that differs from the user's current language settings.
        /// Specify nil to use the user's default locale information. It's valid only if you are using apple services.
        public var locale: String?
        
        /// Return all the servicer params as query items.
        ///
        /// - Returns: [URLQueryItem]
        func serverParams() -> [URLQueryItem] {
            return params.map({ (key,value) in
                URLQueryItem(name: key, value: value)
            })
        }
        public init() {
            
        }
    }
```

Go to Pods -> SwiftLocation -> Geocoder+Support.swift -> find class name "class Options " 
i have added only in existing code, public init() {}, you can directly paste my code as well, clear derived data and build and reopen your project, then it will resolve your problem. 
let me if it will be resolved or not.
