### ISSUE TITLE
locateFromGPS .oneShot always timesout

### ISSUE THREAD

**Issue by goalguy10** [malcommac/SwiftLocation#264]
I am attempting to get the users current location using locateFromGPS(.oneShot, accuracy: .room) but it always times out and returns lastLocation which ends up being the current location. Is this normal behavior or an issue?

**Comment by SergejLogis** [comment]
We are experiencing a similar issue since the last update - for _some_ devices, location resolving (block accuracty, 30 seconds timeout) always timeouts. But for some, it works just fine (at the very same place with the very same app build) 🤔Any ideas?

**Comment by malcommac** [comment]
I think it's related to the GPS module. Did you try using classic `CLLocationManager`? Consider `room` is 5meters within the last 5 seconds. It's a very short, high accuracy value (I start thinking its too strict to be satisfied in that amount of time).

**Comment by goalguy10** [comment]
Sorry for the delayed response. The classic `CLLocationManager` works.
