### ISSUE TITLE
Remove Blue Bar when app is in background.

### ISSUE THREAD

**Issue by arqambutt** [malcommac/SwiftLocation#269]
App is showing blue bar on **"When in Use Usage Description"**. when i select always mode it does not show. How should is remove this blue bar?

**Comment by malcommac** [comment]
It's managed by the system.
After iOS 11 update that blue bar is showing when app is running on the background. What you can do is, track user location when app is in the foreground.
[Check this](https://developer.apple.com/documentation/corelocation/cllocationmanager/2923541-showsbackgroundlocationindicator).
