### ISSUE TITLE
No such module 'SwiftLocation'

### ISSUE THREAD

**Issue by brubom** [malcommac/SwiftLocation#270]
Hey guys,

I'm getting a No such module 'SwiftLocation' after importing the library using cocoa pods (which finishes successfully).

Xcode version: Version 11.1
platform :ios, '13.1'
'SwiftLocation', '~> 4.0'

Thanks

**Comment by mehulparmar4ever** [comment]
Hey @brubom 

**Please update your pod file like this and install pod again.**

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target ‘ProjectName’ do
    #Efficient/Easy GPS tracking, reverse geocoding, region monitoring autocomplete, beacon for iOS
    pod 'SwiftLocation'
end
```

Happy Coding!!
