### ISSUE TITLE
SPM: XCode 11 only available in iOS 9 errors

### ISSUE THREAD

**Issue by coffee-cup** [malcommac/SwiftLocation#271]
I am using SwiftLocation in my app via the swift package manager.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/3044853/68074287-59315000-fd91-11e9-99e2-70d305af7580.png">

I have XCode 11/Swift 5 with the deployment target set to 13.2

<img width="832" alt="image" src="https://user-images.githubusercontent.com/3044853/68074317-9e558200-fd91-11e9-9ab3-3ae2062198c0.png">

When I build I am getting multiple "only available in iOS 9+" errors

<img width="267" alt="image" src="https://user-images.githubusercontent.com/3044853/68074308-8da50c00-fd91-11e9-9a25-3fedc8f2de26.png">

I have no idea why these errors are occurring because the minimum deployment target should be greater than iOS 9. This may not be an issue with SwiftLocation itself, but I wasn't sure where else to ask/look. Any help or advice on fixing this would be greatly appreciated.

**Comment by phongleq** [comment]
He forgot to add a minimum to the package file. I created a PR that should fix this. https://github.com/malcommac/SwiftLocation/pull/274

**Comment by malcommac** [comment]
Merged for 4.2.0
Thank you @phongleq
