### ISSUE TITLE
How to make the blue-pill (location indicator) not visible anymore

### ISSUE THREAD

**Issue by digitxo** [malcommac/SwiftLocation#273]
it seems ".showsBackgroundLocationIndicator = false" should hide the blue pill - but it does not. how do I hide the blue pill

**Comment by malcommac** [comment]
According to Apple doc: `When-in-use authorized` apps will continue showing the Blue Bar as before.
No other service will turn on the Blue Bar. When an app which makes use of any other location service receives an occasional update (for example Significant Location Change), the location arrow on the status bar will momentarily blink solid, but the Blue Bar will not appear.​
