### ISSUE TITLE
LocationManager.shared.locateFromGPS never return success/failure completion

### ISSUE THREAD

**Issue by eminisrafil** [malcommac/SwiftLocation#275]
Similar to this bug: https://github.com/malcommac/SwiftLocation/issues/265

but when I call
`LocationManager.shared.locateFromGPS(.continous, accuracy: .house, activity: .fitness)`
 I sometimes never get the success failure callback. 

Might be an issue in 4.1.0

**Comment by malcommac** [comment]
See the #265 i'll close it.
