### ISSUE TITLE
continuous location monitoring with fixed minimum time interval / min distance

### ISSUE THREAD

**Issue by shrikant8787** [malcommac/SwiftLocation#279]
Hi Team,

I am looking for help/guidance in using the SwiftLocation library.

I  implemented background location tracking. The problem is the location is not updated as per the given minimum interval. The locations that I am getting are inconsistent e.g. If my minimum interval is 120 seconds, then the location event happens randomly, within 2 minutes  I am getting locations with every 15 seconds of time intervals.
I tried it for different intervals and accuracy but I still see inconsistent behavior.
Has anybody experienced similar behavior? 
Please let me know.

My code snippet

let request = LocationManager.shared.locateFromGPS(.continous, accuracy: .house) { data in
            switch data {
            case .failure(let error):
                print("Location error: \(error)")
            case .success(let location):
                //print("New Location: \(location)")    
            }
        }
        request.dataFrequency = .fixed(minInterval: 60, minDistance: 0)

I am using **pod 'SwiftLocation', '~> 4.1.0'**

**Comment by mehulparmar4ever** [comment]
Hi,

I am also facing same issue.

I tried many things, but only work below code. Some **accuracy** is not working in my code. I tried possible solution.


@malcommac , You should use default **accuracy** in location manager instead of ([.any, .city, .neighborhood, .block, .house, .room]) I am stuck from last 2 days.

Below solution is working but I want  **accuracy**: neighborhood/block/house. But it is not working in my case also. 

```
LocationManager.shared.locateFromGPS(.continous,
                                                                     accuracy: .room,
                                                                     activity: .automotiveNavigation)
```

**Comment by artem-krachulov-paysera** [comment]
Same thing 
```
let request = LocationManager.shared.locateFromGPS(.continous, accuracy: .house) { data in  ... }
request.dataFrequency = .fixed(minInterval: 60, minDistance: nil)
```
log
```
...
2020-04-15 12:28:54
2020-04-15 12:28:53
2020-04-15 12:28:52
2020-04-15 12:27:02
2020-04-15 12:27:01
```

every second

**Comment by antonioreyna** [comment]
any solution here?

**Comment by mehulparmar4ever** [comment]
Solution: Use default location functions of CLLocation & You will get location updates on delegate methods.

Only Use this library to fetch address from location. 

**Don't use this library to get locations, use library for fetch address from location.**
