### ISSUE TITLE
Significant change location implemented

### ISSUE THREAD

**Issue by Heki2017** [malcommac/SwiftLocation#283]
L.s.,

I love this pod and I am really happy with it. For further building my app, I found, I need 'Significant change location' service from iOS and was wondering if this is already build in or can be build in. This would enable my app to be switched off, but based on location change to start automatically in the background, process the location and exit again.

https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html

**Comment by samuelail** [comment]
This feature is already mentioned in the docs.  Add this code to your AppDelegate.swift file

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
  /// If you start monitoring significant location changes and your app is subsequently terminated,
  /// the system automatically relaunches the app into the background if a new event arrives.
  // Upon relaunch, you must still subscribe to significant location changes to continue receiving location events.
  if let _ = launchOptions?[UIApplicationLaunchOptionsKey.location] {
    LocationManager.shared.locateFromGPS(.significant, accuracy: .any) { data in
      // ....
   }
 }
}

**Comment by Heki2017** [comment]
> This feature is already mentioned in the docs. Add this code to your AppDelegate.swift file
> 
> func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
> /// If you start monitoring significant location changes and your app is subsequently terminated,
> /// the system automatically relaunches the app into the background if a new event arrives.
> // Upon relaunch, you must still subscribe to significant location changes to continue receiving location events.
> if let _ = launchOptions?[UIApplicationLaunchOptionsKey.location] {
> LocationManager.shared.locateFromGPS(.significant, accuracy: .any) { data in
> // ....
> }
> }
> }

Thanks very much, very happy to hear.
