### ISSUE TITLE
Xcode 11.4 beta2 Support.

### ISSUE THREAD

**Issue by yadav-anil92** [malcommac/SwiftLocation#284]
I got an error following error while compiling the project in XCode 11.4 beta2.

![Screenshot 2020-02-22 at 7 50 16 PM](https://user-images.githubusercontent.com/45240311/75093965-a9d0f100-55ac-11ea-9341-5a301a977ffd.png)

could you please guide me on. how to resolve it?

**Comment by samuelail** [comment]
Try changing the build system to Legacy Build system.  File > Workspace settings > Build System

**Comment by yadav-anil92** [comment]
@samuelail 
ok Thank you
