### ISSUE TITLE
'GeocoderRequest.OpenStreetOptions' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by adamisrafil** [malcommac/SwiftLocation#287]
I am trying to use OpenStreets as the service for my call to locateFromCoordinates. I followed the instructions for declaring the options however I am getting the following error:
`'GeocoderRequest.OpenStreetOptions' initializer is inaccessible due to 'internal' protection level`

Here is the code:

```
let options = GeocoderRequest.OpenStreetOptions() // this is the line with the error
options.limit = 1
LocationManager.shared.locateFromCoordinates(cooridnates, service: .openStreet(options)) { result in
    switch result { ... }
```

This is what is shown in the example but it doesn't work for me.

![Screen Shot 2020-03-15 at 2 32 49 PM](https://user-images.githubusercontent.com/8085293/76707990-e71b3100-66c9-11ea-9de8-63055507e0c3.png)

I am running version pod 4.2.0.

How can I resolve this issue? Is it a bug?

**Comment by rchatham** [comment]
It's as simple as editing the pod and adding public to the initializer. You'll have to tell your project to unlock the Pod for editing though. There should be a more permanent fix though.
