### ISSUE TITLE
Not working : LocationManager.shared.locateFromGPS

### ISSUE THREAD

**Issue by mehulparmar4ever** [malcommac/SwiftLocation#288]
**I tried below method in diff diff way but not working in real device as well as in Simulator.**
_wasted my 2 days to try and find all possible filter and solution in below method_

NOT WORKING ANYMORE :-(

```
        _ = LocationManager.shared.locateFromGPS(.continous, 
accuracy:.custom(kCLLocationAccuracyBestForNavigation), 
activity: .automotiveNavigation)
```

**Comment by vaibhav-jhaveri-ds** [comment]
@mehulparmar4ever @malcommac Any updates on this?
