### ISSUE TITLE
Geofence Region Monitoring 

### ISSUE THREAD

**Issue by DevPravin** [malcommac/SwiftLocation#290]
Hi, 

Does SwiftLocation project supports Geofence Region monitoring? OR
How to achieve below functionality using SwiftLocation project?

   let cRegion = CLCircularRegion(center: location.coordinate, radius: 180.0, identifier: "identifer")
   cRegion.notifyOnEntry = true
   cRegion.notifyOnExit = true
   locationManager.startMonitoring(for: cRegion)

Thanks & Regards,
Pravin

**Comment by malcommac** [comment]
Yes since 5.0 we support geofencing. take a look at the doc.

**Comment by otymartin** [comment]
@malcommac  Do you still stand by this? `custom polygon region (actually it does not work correctly so avoid it)` 🤔
