### ISSUE TITLE
dead ?

### ISSUE THREAD

**Issue by ahmedsafadii** [malcommac/SwiftLocation#298]
is it will be a dead library ?

**Comment by malcommac** [comment]
Nope, I'm writing a major update these weeks. Hope to get something finished by mid oct

**Comment by ahmedsafadii** [comment]
good cuz it's the best library for now <3

**Comment by eminisrafil** [comment]
@malcommac Thank you for your service :)

**Comment by jkpatel1463** [comment]
@malcommac I haven't used this lib, but it seems nice one.

**Comment by malcommac** [comment]
I've just updated the library to 5.0.0; it's a major refactor but it's straightforward to move to the new version.
