### ISSUE TITLE
'rangedRegions' is only available in Mac Catalyst 14.0 or newer

### ISSUE THREAD

**Issue by appfrilans** [malcommac/SwiftLocation#303]
There seem to be an issue on Mac Catalyst. I get the following errors compiling for Mac Catalyst:

`'rangedRegions' is only available in Mac Catalyst 14.0 or newer`

and

`startRangingBeacons(in:)' is only available in Mac Catalyst 14.0 or newer`

and

`'stopRangingBeacons(in:)' is only available in Mac Catalyst 14.0 or newer`

There options are only available (and deprecated) in iOS 14. The framework however targets iOS 11, which gives the error.

These checks should either be conditionalized for iOS 14 or better "iOS or MacCatalyst14"

**Comment by malcommac** [comment]
Thank you, I've just merged your PR
