### ISSUE TITLE
iOS 9 Background location

### ISSUE THREAD

**Issue by ProudOfZiggy** [malcommac/SwiftLocation#31]
I don't seen any usage of allowsBackgroundLocationUpdates of CLLocationManager in you library.

Since iOS 9 you need to set allowsBackgroundLocationUpdates = true to allow location updates while app in background mode.

**Comment by santiguillen** [comment]
+1

**Comment by efremidze** [comment]
:+1:

**Comment by malcommac** [comment]
Added since 0.9.0. Thank you.
