### ISSUE TITLE
Expose allowsBackgroundLocationUpdates and pausesLocationUpdatesAutomatically property to SwiftLocation

### ISSUE THREAD

**Issue by malcommac** [malcommac/SwiftLocation#313]
We should expose:

- `pausesLocationUpdatesAutomatically`: Indicate whether the app should receive location updates when suspended.
- `allowsBackgroundLocationUpdates`: Indicate whether the app should receive location updates when suspended.

**Comment by efremidze** [comment]
Is this exposed in 6.0.0?
