### ISSUE TITLE
minTimeInterval does not seem to work

### ISSUE THREAD

**Issue by jerometonnelier** [malcommac/SwiftLocation#317]
Hi all ;-)

First of all, awesome library ;-)

I have I think what can be an issue : the minTimeInterval does not seem to work.
I use an external option value since the builder does not currently work

```
let serviceOptions = GPSLocationOptions()
        serviceOptions.subscription = .continous // continous updated until you stop it
        serviceOptions.accuracy = .house
        serviceOptions.minDistance = 10
        serviceOptions.minTimeInterval = Defaults[\.locationUpdateRefreshRate] // updated each 30 seconds or more
        serviceOptions.activityType = .automotiveNavigation
        
        locationRequest = SwiftLocation.gpsLocationWith(serviceOptions)
```

I get a location every 10 meters or so. 
Defaults[\.locationUpdateRefreshRate] is set to 15. If I remove the minDistance option, I get a location every seconds or so, not every 15 seconds as I should expect. 

Did I not understand the minTimeInterval correctly or is it a bug ?

Thanks

**Comment by hamzaozturk** [comment]
Related to the issue #318

**Comment by malcommac** [comment]
I'll close it because it's the same problem of #318 as you said.
