### ISSUE TITLE
Wrong timeoutInterval description in Demo Project for GPSRequest

### ISSUE THREAD

**Issue by hamzaozturk** [malcommac/SwiftLocation#319]
https://github.com/malcommac/SwiftLocation/blob/bcbf8d157c6adcd4c9f589f5ba7cf527b94c782a/SwiftLocationPlayground/SwiftLocationPlayground/View%20Controllers/Features/Location%20by%20GPS/GPSController.swift#L97

it has been set with wrong value on ui.

**Comment by malcommac** [comment]
Just fixed in 5.0.3
