### ISSUE TITLE
How to get [GeoLocation] values.

### ISSUE THREAD

**Issue by LoopingLouieX** [malcommac/SwiftLocation#323]
Sorry but I don't understand how to get specific values out of [GeoLocation] with Geocode (Google).
The first thing I don't understand is why there is soo much information in the result with just one coordinate:
I've the following code:
```
        let service = Geocoder.Google(lat: 37.331656, lng: -122.0301426, APIKey: "XYZ")
        SwiftLocation.geocodeWith(service).then { result in

        }
```
If I print `result.data` I get the following:

Optional([{ 
	coordinates = lat:37.3318641,lng:-122.0302537,
	name=Optional("1 Infinite Loop, Cupertino, CA 95014, USA")
	name = '1 Infinite Loop, Cupertino, CA 95014, USA'
	locality = 'Cupertino'
	id = 'ChIJHTRqF7e1j4ARzZ_Fv8VA4Eo'
	country = 'United States'
	intersection = ''
	subAdministrativeArea5 = ''
	streetAddress = ''
	subAdministrativeArea = 'Santa Clara County'
	countryCode = 'US'
	throughfare = 'Infinite Loop'
	subAdministrativeArea3 = ''
	subAdministrativeArea4 = ''
	locationType = 'ROOFTOP'
	administrativeArea = 'California'
	formattedAddress = '1 Infinite Loop, Cupertino, CA 95014, USA'
	postalCode = '95014'
}, { 
	coordinates = lat:37.3318598,lng:-122.0302485,
	name=Optional("Infinite Loop 1, 1 Infinite Loop, Cupertino, CA 95014, USA")
	id = 'ChIJAf9D3La1j4ARuwKZtGjgMXw'
	countryCode = 'US'
	intersection = ''
	country = 'United States'
	name = 'Infinite Loop 1, 1 Infinite Loop, Cupertino, CA 95014, USA'
	formattedAddress = 'Infinite Loop 1, 1 Infinite Loop, Cupertino, CA 95014, USA'
	subAdministrativeArea5 = ''
	administrativeArea = 'California'
	subAdministrativeArea4 = ''
	subAdministrativeArea = 'Santa Clara County'
	postalCode = '95014'
	throughfare = 'Infinite Loop'
	locationType = 'ROOFTOP'
	streetAddress = ''
	subAdministrativeArea3 = ''
	locality = 'Cupertino'
}, { 
	coordinates = lat:37.331652,lng:-122.0307829,
	name=Optional("89 Infinite Loop, Cupertino, CA 95014, USA")
	id = 'Eio4OSBJbmZpbml0ZsdXBlcnRpbm8sIENaUcbDtrWPgBEJVC4KUwn6NhBZ'
	formattedAddress = '89 Infinite Loop, Cupertino, CA 95014, USA'
	streetAddress = ''
	country = 'United States'
	locality = 'Cupertino'
	throughfare = 'Infinite Loop'
	subAdministrativeArea3 = ''
	subAdministrativeArea4 = ''
	countryCode = 'US'
	name = '89 Infinite Loop, Cupertino, CA 95014, USA'
	subAdministrativeArea = 'Santa Clara County'
	subAdministrativeArea5 = ''
	postalCode = '95014'
	intersection = ''
	administrativeArea = 'California'
	locationType = 'RANGE_INTERPOLATED'
}, { 
	coordinates = lat:37.3315439,lng:-122.0307824,
	name=Optional("98-46 Infinite Loop, Cupertino, CA 95014, USA")
	streetAddress = ''
	subAdministrativeArea3 = ''
	subAdministrativeArea = 'Santa Clara County'
	locationType = 'GEOMETRIC_CENTER'
	intersection = ''
	countryCode = 'US'
	subAdministrativeArea4 = ''
	name = '98-46 Infinite Loop, Cupertino, CA 95014, USA'
	postalCode = '95014'
	id = 'ChIJP1HGw7a1j4ARCFQuClMJ-jY'
	formattedAddress = '98-46 Infinite Loop, Cupertino, CA 95014, USA'
	administrativeArea = 'California'
	subAdministrativeArea5 = ''
	country = 'United States'
	throughfare = 'Infinite Loop'
	locality = 'Cupertino'
}, { 
	coordinates = lat:37.3229978,lng:-122.0321823,
	name=Optional("Cupertino, CA, USA")
	id = 'ChIJq3fTG1e0j4ARtHjho-E_TTk'
	intersection = ''
	subAdministrativeArea4 = ''
	streetAddress = ''
	locality = 'Cupertino'
	formattedAddress = 'Cupertino, CA, USA'
	subAdministrativeArea = 'Santa Clara County'
	throughfare = ''
	subAdministrativeArea3 = ''
	name = 'Cupertino, CA, USA'
	country = 'United States'
	administrativeArea = 'California'
	countryCode = 'US'
	subAdministrativeArea5 = ''
	postalCode = ''
	locationType = 'APPROXIMATE'
}, { 
	coordinates = lat:37.31317,lng:-122.0723816,
	name=Optional("MONTE VISTA, CA 95014, USA")
	subAdministrativeArea = 'Santa Clara County'
	subAdministrativeArea3 = ''
	locationType = 'APPROXIMATE'
	id = 'ChIJyTSQVXm0j4ARmdUQoA1BpwQ'
	intersection = ''
	formattedAddress = 'MONTE VISTA, CA 95014, USA'
	country = 'United States'
	subAdministrativeArea5 = ''
	name = 'MONTE VISTA, CA 95014, USA'
	administrativeArea = 'California'
	postalCode = '95014'
	countryCode = 'US'
	throughfare = ''
	streetAddress = ''
	subAdministrativeArea4 = ''
	locality = 'MONTE VISTA'
}, { 
	coordinates = lat:37.3336581,lng:-121.8907041,
	name=Optional("Santa Clara County, CA, USA")
	postalCode = ''
	subAdministrativeArea5 = ''
	locationType = 'APPROXIMATE'
	subAdministrativeArea = 'Santa Clara County'
	locality = ''
	streetAddress = ''
	subAdministrativeArea4 = ''
	administrativeArea = 'California'
	country = 'United States'
	subAdministrativeArea3 = ''
	intersection = ''
	name = 'Santa Clara County, CA, USA'
	id = 'ChIJd_Y0eVIvkIARuQyDN0F1LBA'
	formattedAddress = 'Santa Clara County, CA, USA'
	throughfare = ''
	countryCode = 'US'
}, { 
	coordinates = lat:36.778261,lng:-119.4179324,
	name=Optional("California, USA")
	name = 'California, USA'
	subAdministrativeArea5 = ''
	locality = ''
	subAdministrativeArea3 = ''
	country = 'United States'
	subAdministrativeArea4 = ''
	throughfare = ''
	id = 'ChIJPV4oX_65j4ARVW8IJ6IJUYs'
	countryCode = 'US'
	administrativeArea = 'California'
	subAdministrativeArea = ''
	postalCode = ''
	intersection = ''
	streetAddress = ''
	formattedAddress = 'California, USA'
	locationType = 'APPROXIMATE'
}, { 
	coordinates = lat:37.09024,lng:-95.712891,
	name=Optional("United States")
	administrativeArea = ''
	subAdministrativeArea = ''
	subAdministrativeArea5 = ''
	intersection = ''
	locationType = 'APPROXIMATE'
	subAdministrativeArea4 = ''
	id = 'ChIJCzYy5IS16lQRQrfeQ5K5Oxw'
	subAdministrativeArea3 = ''
	throughfare = ''
	countryCode = 'US'
	locality = ''
	country = 'United States'
	streetAddress = ''
	name = 'United States'
	formattedAddress = 'United States'
	postalCode = ''
}, { 
	coordinates = lat:37.331656,lng:-122.0301426,
	name=Optional("8XJ9+MW Cupertino, CA, USA")
	streetAddress = ''
	locality = 'Cupertino'
	id = 'GhIJ1sIstHOqQkAR2E062-2BXsA'
	administrativeArea = 'California'
	throughfare = ''
	countryCode = 'US'
	postalCode = ''
	intersection = ''
	locationType = 'ROOFTOP'
	subAdministrativeArea5 = ''
	subAdministrativeArea3 = ''
	subAdministrativeArea = 'Santa Clara County'
	country = 'United States'
	name = '8XJ9+MW Cupertino, CA, USA'
	subAdministrativeArea4 = ''
	formattedAddress = '8XJ9+MW Cupertino, CA, USA'
}])

**Why is there so much data (for me useless) and with different coordinates?
Is there no possibility to just fetch the locality?
If not how can I get just the locality out of this mess?**
Thanks!

**Comment by LoopingLouieX** [comment]
Any update?

**Comment by Vaishalishunagund** [comment]
To get the locality from first element of GeoLocation array, you can use the following:
result.data[0].info[. locality]

**Comment by Vaishalishunagund** [comment]
> Any update?



> Sorry but I don't understand how to get specific values out of [GeoLocation] with Geocode (Google).
> The first thing I don't understand is why there is soo much information in the result with just one coordinate:
> I've the following code:
> 
> ```
>         let service = Geocoder.Google(lat: 37.331656, lng: -122.0301426, APIKey: "XYZ")
>         SwiftLocation.geocodeWith(service).then { result in
> 
>         }
> ```
> 
> If I print `result.data` I get the following:
> 
> Optional([{
> coordinates = lat:37.3318641,lng:-122.0302537,
> name=Optional("1 Infinite Loop, Cupertino, CA 95014, USA")
> name = '1 Infinite Loop, Cupertino, CA 95014, USA'
> locality = 'Cupertino'
> id = 'ChIJHTRqF7e1j4ARzZ_Fv8VA4Eo'
> country = 'United States'
> intersection = ''
> subAdministrativeArea5 = ''
> streetAddress = ''
> subAdministrativeArea = 'Santa Clara County'
> countryCode = 'US'
> throughfare = 'Infinite Loop'
> subAdministrativeArea3 = ''
> subAdministrativeArea4 = ''
> locationType = 'ROOFTOP'
> administrativeArea = 'California'
> formattedAddress = '1 Infinite Loop, Cupertino, CA 95014, USA'
> postalCode = '95014'
> }, {
> coordinates = lat:37.3318598,lng:-122.0302485,
> name=Optional("Infinite Loop 1, 1 Infinite Loop, Cupertino, CA 95014, USA")
> id = 'ChIJAf9D3La1j4ARuwKZtGjgMXw'
> countryCode = 'US'
> intersection = ''
> country = 'United States'
> name = 'Infinite Loop 1, 1 Infinite Loop, Cupertino, CA 95014, USA'
> formattedAddress = 'Infinite Loop 1, 1 Infinite Loop, Cupertino, CA 95014, USA'
> subAdministrativeArea5 = ''
> administrativeArea = 'California'
> subAdministrativeArea4 = ''
> subAdministrativeArea = 'Santa Clara County'
> postalCode = '95014'
> throughfare = 'Infinite Loop'
> locationType = 'ROOFTOP'
> streetAddress = ''
> subAdministrativeArea3 = ''
> locality = 'Cupertino'
> }, {
> coordinates = lat:37.331652,lng:-122.0307829,
> name=Optional("89 Infinite Loop, Cupertino, CA 95014, USA")
> id = 'Eio4OSBJbmZpbml0ZsdXBlcnRpbm8sIENaUcbDtrWPgBEJVC4KUwn6NhBZ'
> formattedAddress = '89 Infinite Loop, Cupertino, CA 95014, USA'
> streetAddress = ''
> country = 'United States'
> locality = 'Cupertino'
> throughfare = 'Infinite Loop'
> subAdministrativeArea3 = ''
> subAdministrativeArea4 = ''
> countryCode = 'US'
> name = '89 Infinite Loop, Cupertino, CA 95014, USA'
> subAdministrativeArea = 'Santa Clara County'
> subAdministrativeArea5 = ''
> postalCode = '95014'
> intersection = ''
> administrativeArea = 'California'
> locationType = 'RANGE_INTERPOLATED'
> }, {
> coordinates = lat:37.3315439,lng:-122.0307824,
> name=Optional("98-46 Infinite Loop, Cupertino, CA 95014, USA")
> streetAddress = ''
> subAdministrativeArea3 = ''
> subAdministrativeArea = 'Santa Clara County'
> locationType = 'GEOMETRIC_CENTER'
> intersection = ''
> countryCode = 'US'
> subAdministrativeArea4 = ''
> name = '98-46 Infinite Loop, Cupertino, CA 95014, USA'
> postalCode = '95014'
> id = 'ChIJP1HGw7a1j4ARCFQuClMJ-jY'
> formattedAddress = '98-46 Infinite Loop, Cupertino, CA 95014, USA'
> administrativeArea = 'California'
> subAdministrativeArea5 = ''
> country = 'United States'
> throughfare = 'Infinite Loop'
> locality = 'Cupertino'
> }, {
> coordinates = lat:37.3229978,lng:-122.0321823,
> name=Optional("Cupertino, CA, USA")
> id = 'ChIJq3fTG1e0j4ARtHjho-E_TTk'
> intersection = ''
> subAdministrativeArea4 = ''
> streetAddress = ''
> locality = 'Cupertino'
> formattedAddress = 'Cupertino, CA, USA'
> subAdministrativeArea = 'Santa Clara County'
> throughfare = ''
> subAdministrativeArea3 = ''
> name = 'Cupertino, CA, USA'
> country = 'United States'
> administrativeArea = 'California'
> countryCode = 'US'
> subAdministrativeArea5 = ''
> postalCode = ''
> locationType = 'APPROXIMATE'
> }, {
> coordinates = lat:37.31317,lng:-122.0723816,
> name=Optional("MONTE VISTA, CA 95014, USA")
> subAdministrativeArea = 'Santa Clara County'
> subAdministrativeArea3 = ''
> locationType = 'APPROXIMATE'
> id = 'ChIJyTSQVXm0j4ARmdUQoA1BpwQ'
> intersection = ''
> formattedAddress = 'MONTE VISTA, CA 95014, USA'
> country = 'United States'
> subAdministrativeArea5 = ''
> name = 'MONTE VISTA, CA 95014, USA'
> administrativeArea = 'California'
> postalCode = '95014'
> countryCode = 'US'
> throughfare = ''
> streetAddress = ''
> subAdministrativeArea4 = ''
> locality = 'MONTE VISTA'
> }, {
> coordinates = lat:37.3336581,lng:-121.8907041,
> name=Optional("Santa Clara County, CA, USA")
> postalCode = ''
> subAdministrativeArea5 = ''
> locationType = 'APPROXIMATE'
> subAdministrativeArea = 'Santa Clara County'
> locality = ''
> streetAddress = ''
> subAdministrativeArea4 = ''
> administrativeArea = 'California'
> country = 'United States'
> subAdministrativeArea3 = ''
> intersection = ''
> name = 'Santa Clara County, CA, USA'
> id = 'ChIJd_Y0eVIvkIARuQyDN0F1LBA'
> formattedAddress = 'Santa Clara County, CA, USA'
> throughfare = ''
> countryCode = 'US'
> }, {
> coordinates = lat:36.778261,lng:-119.4179324,
> name=Optional("California, USA")
> name = 'California, USA'
> subAdministrativeArea5 = ''
> locality = ''
> subAdministrativeArea3 = ''
> country = 'United States'
> subAdministrativeArea4 = ''
> throughfare = ''
> id = 'ChIJPV4oX_65j4ARVW8IJ6IJUYs'
> countryCode = 'US'
> administrativeArea = 'California'
> subAdministrativeArea = ''
> postalCode = ''
> intersection = ''
> streetAddress = ''
> formattedAddress = 'California, USA'
> locationType = 'APPROXIMATE'
> }, {
> coordinates = lat:37.09024,lng:-95.712891,
> name=Optional("United States")
> administrativeArea = ''
> subAdministrativeArea = ''
> subAdministrativeArea5 = ''
> intersection = ''
> locationType = 'APPROXIMATE'
> subAdministrativeArea4 = ''
> id = 'ChIJCzYy5IS16lQRQrfeQ5K5Oxw'
> subAdministrativeArea3 = ''
> throughfare = ''
> countryCode = 'US'
> locality = ''
> country = 'United States'
> streetAddress = ''
> name = 'United States'
> formattedAddress = 'United States'
> postalCode = ''
> }, {
> coordinates = lat:37.331656,lng:-122.0301426,
> name=Optional("8XJ9+MW Cupertino, CA, USA")
> streetAddress = ''
> locality = 'Cupertino'
> id = 'GhIJ1sIstHOqQkAR2E062-2BXsA'
> administrativeArea = 'California'
> throughfare = ''
> countryCode = 'US'
> postalCode = ''
> intersection = ''
> locationType = 'ROOFTOP'
> subAdministrativeArea5 = ''
> subAdministrativeArea3 = ''
> subAdministrativeArea = 'Santa Clara County'
> country = 'United States'
> name = '8XJ9+MW Cupertino, CA, USA'
> subAdministrativeArea4 = ''
> formattedAddress = '8XJ9+MW Cupertino, CA, USA'
> }])
> 
> **Why is there so much data (for me useless) and with different coordinates? Is there no possibility to just fetch the locality? If not how can I get just the locality out of this mess?**
> Thanks!

To get the locality from first element of GeoLocation array, you can use the following:
result.data[0].info[. locality]

**Comment by Vaishalishunagund** [comment]
To get the locality from first element of GeoLocation array, you can use the following:
result.data[0].info[. locality]
