### ISSUE TITLE
Error Processing

### ISSUE THREAD

**Issue by perryhoekstra** [malcommac/SwiftLocation#330]
In the case of:

SwiftLocation.gpsLocation(accuracy: .neighborhood).then { result in
    switch result {
       case .success(let locationData):
         do some successfull processing    
       case .failure( _):
         do some failure processing
    }
}

How do you handle error processing where the result callback is not returned (such as the user stating Don't Allow)?  I did not see that identified in the documentation.

**Comment by hamzaozturk** [comment]
```
SwiftLocation.gpsLocation(accuracy: .neighborhood).then { result in
    switch result {
    case .success(let locationData):
        print(locationData)
    case .failure(let error):
        switch error {
        case .authorizationNeeded:
            //do some failure processing
            break
        default:
            break
        }
    }
}
```

**Comment by perryhoekstra** [comment]
No, if the user selects Don't Allow, it will not fail into .failure case.

**Comment by appfrilans** [comment]
Same here! iOS 15 real device iPhone 12 Pro. Quite important feature.
