### ISSUE TITLE
Error Processing

### ISSUE THREAD

**Issue by perryhoekstra** [malcommac/SwiftLocation#331]
In the case of:

```swift
SwiftLocation.gpsLocation(accuracy: .neighborhood).then { result in
    switch result {
       case .success(let locationData):
         // do some successfull processing    
       case .failure( _):
         // do some failure processing
    }
}
```

How do you handle error processing where the result callback is not returned (such as the user stating Don't Allow)?  I did not see that identified in the documentation.

**Comment by appfrilans** [comment]
Wonders the same. Quite important feature of a framework! May have to find another framework it this one is not fixed! Is it even maintained?
