### ISSUE TITLE
Failure block never executes when user denies the permission.

### ISSUE THREAD

**Issue by coolgary90** [malcommac/SwiftLocation#341]
SwiftLocation.gpsLocation().then { (result) in
            switch result {
                       case .success(let newData):
                           print("New location: \(newData)")
                       case .failure(let error):
                           print("An error has occurred: \(error.localizedDescription)")
                       }
        }

**Comment by twiedow** [comment]
Same here, there is no callback when the user does not authorise location tracking. In my case the app hangs forever.

Does this work as designed (the app has to request authorisation by itself when needed) or is this a bug?

Thanks a lot!

**Comment by ijunfly** [comment]
That should at least return the rejection status?

**Comment by ladmini** [comment]
+1 any update?

**Comment by alexware** [comment]
+1 any news about this? This issue affects my flow when user denies permission. Callback required to unlock next step of my app.
