### ISSUE TITLE
Authorisation change response from setting 

### ISSUE THREAD

**Issue by LetstrackApp** [malcommac/SwiftLocation#344]
previous version library had "LocationManager.shared.onAuthorizationChange.add" method , which gave the status of authorisation change  when user changed the permission from setting app . with this version we did not get this "onAuthorizationChange" type of method, when user change the Authorization from the setting. please help me how can we achieve this functionality in this updated version .

**Comment by rokon-uddin** [comment]
@malcommac could you shed some light on this issue?

**Comment by TheSPST** [comment]
LocationManager.shared.onAuthorizationChange.add this is not available in updated SDK, any alternative for this method in latest version ??

**Comment by drakos** [comment]
Did anyone find a way to get the authorisation change in current lib version? Please respond. Thanks!
