### ISSUE TITLE
How to track heading?

### ISSUE THREAD

**Issue by markerpen** [malcommac/SwiftLocation#345]
Hi there,

Looking through the commits, the previous version (Locator) had the ability to subscribe to CLHeading change events, but I can't see anything in the documentation to do the same with the current (>5.0) version. Is this a custom subscription that's attached to SwiftLocation?

**Comment by otymartin** [comment]
@malcommac Is this still available? `Locator.subscribeHeadingUpdates` I think was the previous method.

**Comment by mouayyadtaja** [comment]
Is there any update here?
