### ISSUE TITLE
Blue bar blink when fetch position

### ISSUE THREAD

**Issue by paul-lavoine** [malcommac/SwiftLocation#346]
Hello,

**Here my configuration:**
- New project to be sure, there is no impact from my code.
- I picked "When-In-Use" authorization
- I call the following method
` SwiftLocation.gpsLocation(accuracy: .block,
                                timeout: .delayed(0)).then { (result) in 
...
}`

When I call this method, the blue bar blink.
How can I avoid this ?

Here a video to understand the behaviour : https://we.tl/t-pTY7LFvnQi

**Comment by ay8s** [comment]
@paul-lavoine I believe iOS is showing the blue bar due to the app using GPS. I wonder if its blinking due to your timeout being 0 seconds.

**Comment by paul-lavoine** [comment]
iOS is showing the blue bar with settings **when-in-use** and when app is in background. That's why I don't understand this behaviour... :( 
I tried with an other timeout but it's  the same result ...

**Comment by paul-lavoine** [comment]
Ok, it's an iOS bug since v14.0
