### ISSUE TITLE
Get location when app is suspended 

### ISSUE THREAD

**Issue by rokon-uddin** [malcommac/SwiftLocation#348]
Hi,
Regarding this PR: https://github.com/malcommac/SwiftLocation/issues/313#ref-commit-1061b81
how I can get the updated location when app suspended? Sets say I want trigger a push notification each time location updates when app is killed or suspended state.

**Comment by doganaltinbas** [comment]
You should enable Location Updates in background modes.
Check this: https://www.hackingwithswift.com/example-code/location/how-to-read-the-users-location-while-your-app-is-in-the-background
