### ISSUE TITLE
How to disable location updates logs?

### ISSUE THREAD

**Issue by ninholli** [malcommac/SwiftLocation#358]
I want to disable all logs from the SDK. But LocationManager.Logger.isEnabled is internal access.

**Comment by taarond** [comment]
i made this one change in a fork and it seems to do the trick.

// SwiftLocation+Errors, line 122
static var isEnabled = false

https://github.com/taarond/SwiftLocation

**Comment by maggnus** [comment]
+1

**Comment by Teglgaard** [comment]
+1
@taarond can you make the variable public and make a PR
