### ISSUE TITLE
Not working with AppClip

### ISSUE THREAD

**Issue by appfrilans** [malcommac/SwiftLocation#369]
Just by importing the library into my app Clip Target in Xcode I get the following error/warning when uploading to TestFlight/AppStore:

ITMS-90842: Invalid SDK usage - App clip 'BuildTarget_AC_Base.app/AppClips/BuildTarget_AppClip.app' uses the SDK selector 'requestAlwaysAuthorization', which is not supported. Ensure your app clip is using supported SDK features.

You can use "#if APPCLIP" to skip code that reference API that are not allowed in AppClips. Is it possible to solve this in the framework as well?

**Comment by Strobocop** [comment]
@malcommac You may want to consider reopening this issue. I have attempted to push an app clip through to testflight with this library as a dependency and have consistently gotten the build flagged:

ITMS-90842: Invalid SDK usage - App clip uses the SDK selector 'requestAlwaysAuthorization', which is not supported. Ensure your app clip is using supported SDK features.

My current theory is that the `APPCLIP` compiler flag doesn't get passed along to the library, as embedding this source directly into my app and app clip works as expected. I think the proper way to fix this would be to split the library into two separate targets, one with always location, and one without, and then the adopting applications can conditoinally link the appropriate one. 

Maybe there is a simpler way to share the context of the APPCLIP flag, but after some basic research on capabilities of SPM, I don't see one.

@appfrilans Are you running into this still?
