### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by happiehappie** [malcommac/SwiftLocation#38]
Sorry if this is a bit amateur but does anyone know how to set the timeout in version 0.9? The documentation stated that LocationRequest also specify a timeoutTimer property you can set to abort the request itself if no valid data is received in a certain amount of time. By default it's disabled.
But XCode tells me that LocationRequest has no member timeoutTimer

**Comment by malcommac** [comment]
Property is `timeout` not `timeoutTimer`. Sorry about that, I'll fix docs.

**Comment by happiehappie** [comment]
Is there a way to handle the timeout? Like is there a callback when a timeout occured? So I can handle appropriately.
