### ISSUE TITLE
Failed to get highest location accuracy using continousLocation

### ISSUE THREAD

**Issue by kiokumicu** [malcommac/SwiftLocation#4]
No location update when use .continuousLocation and Accuracy.Room. When use Accuracy.House work fine.

**Comment by malcommac** [comment]
"Room" accuracy means an accuracy of 5 meters or better, and received within the last 5 seconds.
Are you in indoor? Maybe your GPS signal has not enough strength to provide such accuracy at the moment; can you test it in outdoor?

**Comment by kiokumicu** [comment]
I run GPS simulator in Xcode - Freeway Drive

**Comment by malcommac** [comment]
Checkout 0.1.3 build (available into the master branch or cocoapods with '0.1.3' label).
You error should be fixed.
Thank you
