### ISSUE TITLE
Infinite loop if location disabled

### ISSUE THREAD

**Issue by pballart** [malcommac/SwiftLocation#40]
I'm using the observeLocations method but if the user switched the location of my app to "never" the method starts in infinite loop.

Here you have the stack trace:
![screen shot 2016-05-25 at 17 39 01](https://cloud.githubusercontent.com/assets/1868467/15546289/a6d60dc6-229f-11e6-8888-90215d3b6408.png)

If the location services are granted for my app (Always) it works perfectly but if they are turned off (Never) it crashes.

**Comment by malcommac** [comment]
Hi @pballart , thank you for your report.
I've actually tried to make a test app with always auth, then I've launched the app and turned off location. I get a single error with not infinite loop.
Can you provide to me an example project or step-by-step info?
Thank you

**Comment by pballart** [comment]
Hi @malcommac I finally found the problem. It was my fault. Sorry about that.

**Comment by malcommac** [comment]
No problem 👍

**Comment by ludoded** [comment]
@pballart hi man, I'm experiencing same issue. Can you share what was the problem and how did you solve it, please?

**Comment by pballart** [comment]
Hi @ludoded! I just checked is the location services were enabled before calling the observeLocations method.

**Comment by jyounus** [comment]
I've got the same issue. Since SwiftLocation already seems to handle basic permissions (by requesting permissions if you don't have any already), I think it would make sense if the library would also handle if the user turns off location permissions after giving access.
