### ISSUE TITLE
Update to 0.9.0

### ISSUE THREAD

**Issue by Alexsmile2010** [malcommac/SwiftLocation#41]
When i update cocoapods to version 0.9.0 SwiftLocation.shared stopped working.

**Comment by happiehappie** [comment]
Check the documentation or even the examples. It got changed to LocationManager.

**Comment by Alexsmile2010** [comment]
I saw documentation and it`s alright. Can you update documentation in cocoapods web page?

**Comment by malcommac** [comment]
Just pushed 1.0.0
