### ISSUE TITLE
Question: How to get currency location of another device

### ISSUE THREAD

**Issue by otymartin** [malcommac/SwiftLocation#43]
@malcommac 

Question, How could I use `SwiftLocation` for this scenario (I will user Uber as an example)

`Driver` is delegated to capture a charge (Charge Rider's credit card) at the end of a trip.
The action can only happen if `Rider` is within `Room` distance (Or an arbitrary distance i set).
Else `ERROR: Rider is not within distance`

How can use swift location to so `Driver` can get `Rider's` current location when `Rider's` device is either in `Foreground` or `Background`

**Comment by Kalzem** [comment]
This has nothing to do with SwiftLocation. You need a server for that. Check Firebase for a mobileBaaS (or any other mBaaS).
