### ISSUE TITLE
There is no option to provide our own api Key for google reverse geo location.

### ISSUE THREAD

**Issue by manish-1988** [malcommac/SwiftLocation#44]
I want to provide my own api key to your library and there is no option for that .

**Comment by ServicePal** [comment]
+1 for the ability to add Google API Key. Without it, Google will impose stricter quota.

**Comment by malcommac** [comment]
You are right, I've added a `googleAPIKey` to `LocationManager` class. I'll post a new update in few days.
Thanks you for your suggestion.
