### ISSUE TITLE
Doesn't update heading continuously

### ISSUE THREAD

**Issue by Goktug** [malcommac/SwiftLocation#47]
I faced a problem to try observe my device's heading. 

When I used belove method to observe heading. I couldn't get the heading continuously. `onSuccess` closure triggered rarely.
`LocationManager.shared.observeHeading(onSuccess: onSuccess, onError: onError)`

I looked up the codes I have seen this `if condition`.

`if self.validateHeading(heading!) == true {
            self.lastHeading = heading
            self.onSuccess?(self.lastHeading!)
        }`

When I deleted the `if condition`, the code works well. 
What is the purpose of this code?

**Comment by malcommac** [comment]
Just fixed; i'll release a new update in few days.
Thank you for your report.
