### ISSUE TITLE
Using the name 'Location' ?

### ISSUE THREAD

**Issue by canaksoy** [malcommac/SwiftLocation#51]
Why did you change the name with a generic term 'Location' ?
It cause lots of conflict with other frameworks, classes etc...
You can use a unique name.

**Comment by nmDejamobile** [comment]
@canaksoy You can simply use the SwiftLocation bundle name as prefix for disambiguation : **SwiftLocation.Location**

**Comment by malcommac** [comment]
Yeah that's right, Swift implements module prefix in case you need to make disambiguation
