### ISSUE TITLE
monitorForBeaconFamily / monitorForBeacon -> Crashes with nil exception :: The initializers for the BeaconRequest object seem broken to me?!

### ISSUE THREAD

**Issue by Daij-Djan** [malcommac/SwiftLocation#52]
Hi
monitorForBeaconFamily / monitorForBeacon -> Crashes with nil exception

The initializers for the BeaconRequest object seem broken to me?!
BECAUSE :: they use beaconRegion before assigning it...

see:

```
 self.beaconRegion = CLBeaconRegion(proximityUUID: NSUUID(UUIDString: self.UUID)!, identifier: self.identifier)
```

self.UUID uses the region before it is even assigned:

```
 return beaconRegion!.proximityUUID.UUIDString
```

IMHO this is broken and maybe a typo. self.UUID should be uuid !?

**Comment by malcommac** [comment]
Please refer to #60 . Thanks for your report.
