### ISSUE TITLE
monitoring for ble beacons will never work as the callbacks filter based monitoredGeoRegions

### ISSUE THREAD

**Issue by Daij-Djan** [malcommac/SwiftLocation#56]
Hi,
I discovered monitoring for ble beacons will never work as the callbacks filter based monitoredGeoRegions I fixed it by doubling the code for now ;) .. there should be a common protocol

**Comment by Daij-Djan** [comment]
is this feature even planned? region monitoring for BLE?

**Comment by Daij-Djan** [comment]
don't see how ranging beacons works either .. I did monitoring by adding onRegionX callbacks to BeaconRequest

**Comment by Daij-Djan** [comment]
and monitoring can only work for a family as IOS only uses the uuid for monitoring :) I removed the for beacon for now but it should be readied with a name & functionality to range it

**Comment by Daij-Djan** [comment]
(and just to say it: I don't wanna sound demanding or anything :D just saying stuff as I notice it)

**Comment by Daij-Djan** [comment]
[code.zip](https://github.com/malcommac/SwiftLocation/files/430770/code.zip)

**Comment by Daij-Djan** [comment]
[Archive.zip](https://github.com/malcommac/SwiftLocation/files/430775/Archive.zip)

**Comment by Daij-Djan** [comment]
Ill do a PR later IF you event want it :)

**Comment by malcommac** [comment]
Please refer to #60 . Thanks for your report.
