### ISSUE TITLE
Not working on iOS 10 beta

### ISSUE THREAD

**Issue by ShadeApps** [malcommac/SwiftLocation#63]
Hello and thank you for your great work!

I'm using the provided latest version of the sources and I'm encountering an error on a device running iOS 10 beta 6 in Xcode 7 using Swift 2.2.

Here's [my test project](https://mega.nz/#!u9BGGR4Z!w3cvAlSUxKnXQjckcfIBFtgfCvdQV4yF9DToMFlGny0), maybe you could tell me what's wrong.

Works perfectly fine on iOS 9.3.5

**Comment by malcommac** [comment]
Hi @ShadeApps ,
Thank you! I've the latest iOS 10 beta 8, I can make a test with it...but I think I can't run a project using XCode 7.3.1 under iOS 10 beta; it simply say "Could not find Developer Disk Image".
Have you a solution?
However I need to convert 1.0.3 release both for Swift 2.3 and 3.0; I'll do it in these days.

**Comment by ShadeApps** [comment]
@malcommac sure, check it out - http://stackoverflow.com/a/37940175/1313939

**Comment by malcommac** [comment]
Cool!
Just tried and here it works fine.
He hasked to me auth and then I get location:

`<+41.850768,+12.404162> +/- 65.00m (speed -1.00 mps / course -1.00) @ 27/08/16, 14:37:01 Ora legale dell’Europa centrale`

(Here I'm with iOS 10 beta 8/Xcode 7.3.1)

**Comment by ShadeApps** [comment]
Awesome! I'll update the beta today and confirm if it works, thank you for the feedback.

**Comment by malcommac** [comment]
Can I close it?

**Comment by ShadeApps** [comment]
Sure, I can confirm it works.
Thanks.

От 31 августа 2016 г. в 21:08:05, Daniele Margutti (notifications@github.com) написал:

Can I close it?

**Comment by malcommac** [comment]
Thanks
