### ISSUE TITLE
Swift 3 build errors

### ISSUE THREAD

**Issue by mohpor** [malcommac/SwiftLocation#65]
I am trying out this framework for my future project (it looks great), but unfortunately the test project I have started (Using Cocoapods (1.1.0.beta 1) with: 

```
pod 'SwiftLocation' :git: => 'https://github.com/malcommac/SwiftLocation.git', :branch => 'feature/swift3'
```

 doesn't build. There is two different type of errors and 15 errors overall:
1.  Some declarations are missing, among them are: `RegionHandlerStateDidChange`, `RegionHandlerStateDidChange`, `RegionHandlerError`, ...
2.  `Beacon` has two declarations. One in `BeaconManager.swift` and the other one in `Common.swift`

I'm guessing you are testing and building your project without the pods (have you used `pod lib create ...`?) This is always error prone.

Could you take a look. I'm lost a bit. There are files in my pod that have not been added to your test project. 😖

**Comment by malcommac** [comment]
I'm sorry, there was a problem with merge. I'll fix it later today.

**Comment by mohpor** [comment]
No problem at all 👍 
Thanks for the effort, this is a decent library.

**Comment by mohpor** [comment]
@malcommac It seems like Swift 3 branch is broken. I still cannot use the branch in pod and I can see so many differences to the base implementation of the Swift3 Branch.

We have 2 options here:  
1. We could rebase the `feature/swift3` branch based on `master`
2. Get rid of `feature/swift3` branch and migrate the current `master` branch to Swift 3.0.  
Personally I prefer the second approach because we can control the migration and it will be easier/cleaner.

I think Swift 3.0 GM is upon us and a working Swift 3.0 compatible code base is only reasonable.

**Comment by mgfeldman** [comment]
@malcommac I'm also still getting the same errors on the swift3 branch.

**Comment by robbiet480** [comment]
I thought I could get away with an easy rebase. I prayed to Linus to make it so. But here I am, 45 minutes in, with no end in sight.

I would strongly suggest option 2 that @mohpor suggested.

**Comment by mohpor** [comment]
@robbiet480 😆 😆 You had me at `prayed to Linus` he would love to hear that.

ehem, The conversion should be straight forward. 😎

**Comment by robbiet480** [comment]
Built a new Swift 3 branch off of the latest master, available [here](https://github.com/robbiet480/SwiftLocation/tree/feature/swift3-latest-master).

**Comment by malcommac** [comment]
Merged in [swift-3 ](https://github.com/malcommac/SwiftLocation/tree/swift-3.0)branch.
I'll put in master with a new updated once Swift 3 GM will be released.
Thanks.
