### ISSUE TITLE
.IPScan accuracy needs NSAppTransportSecurity

### ISSUE THREAD

**Issue by mohpor** [malcommac/SwiftLocation#66]
The URL call for `.IPScan` points to an `http` address which is prohibited by default. We should enable such calls in the app to be able to call the API and get the results.

I'll make a PR to point this out in the README file.

**Comment by mohpor** [comment]
Upon further reading, I'm now concerned about anybody using this library in a commercial application. [ip-api.com](http://ip-api.com) clearly states that there is a [usage limit](http://ip-api.com/docs/#usage_limits) (150 request per IP per minute) and commercial applications need to go [pro](https://signup.ip-api.com), in which case they can use SSL (which is slower and I don't recommend for location lookup)

**Comment by ServicePal** [comment]
Please explain, what do you mean by "prohibited by default" ?

I don't share your commercial concern. I can imagine many apps which does not make 150 request per minute from the same IP address. Their PRO feature seems reasonable priced for people who do.

**Comment by mohpor** [comment]
On iOS 9+, you need special setting in `info.plist` to be able to call any URL with `http` protocol. ([Read Here](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33))

About the commercial concern, I'm not concerned for myself, but for anybody who'd use this library. You see, this library uses an API which might have consequences for anybody who is using it, we should at least warn them. That's all I'm saying. And yes, their pricing is quite reasonable, and I think we should allow settings for pro users (just like Google's API key) in the framework.

**Comment by ServicePal** [comment]
Gotcha. iOS 9 SDK requirement. Agree on the commercial comment as well. Thanks for your contributions.

**Comment by malcommac** [comment]
Thank you for your PR. I've ported them to Swift 2.2 branch
