### ISSUE TITLE
"Invalid redeclaration of Beacon" when upgrading to Swift2.3 branch

### ISSUE THREAD

**Issue by andreabusi** [malcommac/SwiftLocation#72]
Hi,
I've tried to update to feature/swift2.3 branch (with Xcode 8), but I obtained these errors:

![screen shot 2016-09-08 at 17 42 17](https://cloud.githubusercontent.com/assets/847860/18356072/a21febd6-75eb-11e6-99c8-c3e3e90e8ec1.png)

Am I missing something? 
Here is the pod I use:

`pod 'SwiftLocation', :git => 'https://github.com/malcommac/SwiftLocation.git', :branch => 'feature/swift2.3'`

Thanks!

**Comment by malcommac** [comment]
Just fixed and aligned to 1.0.5 (latest version for Swift 2.2 and 2.3).
Make a `pod update` and try again.
Thanks for the report

**Comment by andreabusi** [comment]
Solved, thanks!
