### ISSUE TITLE
Small fix for Swift2.3

### ISSUE THREAD

**Issue by glancashire** [malcommac/SwiftLocation#75]
First thanks for the great work.

There is a small issue in Swift 2.3.

In BeaconsManager.swift in the function
@objc public func peripheralManagerDidUpdateState(peripheral: CBPeripheralManager) {

please change the line to  
if peripheral.state == .PoweredOn {

Kind Regards
Graham

**Comment by malcommac** [comment]
See in switch-2.3 branch for Swift 2.3 (https://github.com/malcommac/SwiftLocation/tree/feature/swift2.3)
It's already changed:
https://github.com/malcommac/SwiftLocation/blob/feature/swift2.3/src/BeaconManager.swift#L287

**Comment by glancashire** [comment]
Thanks
Graham
