### ISSUE TITLE
allowsBackgroundLocationUpdates

### ISSUE THREAD

**Issue by swabzz** [malcommac/SwiftLocation#76]
Can you please help me to get location when application in background mode.
I am having Google Map integrated in my app and confused in getting location in background.

Thanks in advance

**Comment by manish-1988** [comment]
Background is working totally fine with me 
But I am stuck in updating location while app is terminated 
@malcommac  If you can clear that whether I can implement this feature using you library ? 
Thank you so much for this library helped me a lot already.

**Comment by swabzz** [comment]
@manish-1988 
How you manage to get location in background??
can you post your code here please?

**Comment by manish-1988** [comment]
You should ask this question in **stackOverflow** only not here , but since I also did asked a question here is the standard solution to your query

**Step - 0** Open pList as source code and add these lines in your code.
    <key>NSLocationAlwaysUsageDescription</key>
    <string>This App requires your location</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>This App requires your location</string>

**Step 1** - In target - capabilities 
Switch on the location updates in background mode, regenerate provisioning profile if needed.

Step II - Request for authorization
& Initialize locationManager
    /// MARK:- LOCATION MANAGER INITIALIZATION

```
    func initLocationManager(target: UIViewController)
    {
        self.locationManager = CLLocationManager()

        self.locationManager.delegate = self

        self.locationManager.distanceFilter = CLLocationDistance(50.0)

        self.locationManager.requestAlwaysAuthorization()

        self.locationManager.desiredAccuracy = kCLLocationAccuracyBest

        self.locationManager.startMonitoringSignificantLocationChanges()

        if #available(iOS 9.0, *)
        {
            self.locationManager.allowsBackgroundLocationUpdates = true
        } else
        {
            // Fallback on earlier versions
        }

        if (CLLocationManager.locationServicesEnabled())
        {
            switch(CLLocationManager.authorizationStatus())
            {
            case .NotDetermined:

                print("NotDetermined")

            case .Restricted:

                print("Restricted")

                Singleton.sharedInstance.showLocationAlert(target)

            case .Denied:

                print("Denied")

                Singleton.sharedInstance.showLocationAlert(target)

            case .AuthorizedAlways, .AuthorizedWhenInUse:

                print("Location Service => AuthorizedAlways | AuthorizedWhenInUse")

                self.locationManager.startUpdatingLocation()

            }
        }else
        {
            //Yet nothing to do in this condition
        }
    }
```

This below delgate will be called even in background if device gets location update.

```
    func locationManager(manager: CLLocationManager, didUpdateLocations locations: [CLLocation])
     {
         **// Here you can send your location to server using webService.**
     }
```

**Comment by swabzz** [comment]
Thanks Manish,

Is this solution valid for SwiftLocation Library???

I mean i have SwiftLocation library installed so do i need to do all above procedure to get location in background??

Thanks again for your quick response.

**Comment by manish-1988** [comment]
In any case you need to perform the target - capabilities thing and plist thing I mentioned in my above answer rest,
If you want to use this library it is clearly mention in the documentation how to do it.
You just need to add this 

> SwiftLocation works even in background; just use Location.allowsBackgroundEvents = true (don't forget to define UIBackgroundModes array).
> So
> There is a property Location.allowsBackgroundEvents make it true.
> **Following is the code you can use I am using previous version of the library.**
> `
> LocationManager.shared.allowsBackgroundEvents = true // This line is important for you
>  LocationManager.shared.observeLocations(.Room, frequency: .ByDistanceIntervals(meters: 50), onSuccess: { (location) in
>             print(location)
>             }) { (error) in
>                 print(error)
>         }
> `
> Where I have printed the location you will get the update location in every 50 M traveled , you can reduce the distance as per your need.

Do let me know if it works.

**Comment by swabzz** [comment]
Thanks Brother for helping,

will let you know if it works

**Comment by malcommac** [comment]
Could we close it?

**Comment by swabzz** [comment]
Yes, Please and thank for support

**Comment by malcommac** [comment]
No problem, you're welcome. thanks to @manish-1988 for support.

**Comment by swabzz** [comment]
@manish-1988 

did you get solution for updating location even if app is terminated?

**Comment by manish-1988** [comment]
@swabzz  Yes what I did is I have used region monitoring. First I created a background task before app termination and created a region as soon as the device crosses the region, I have created another region from the current coordinates while entering and exiting from regions,  did update location delegate gets called and I get the updated coordinate while application is in terminated mode.

**Comment by swabzz** [comment]
Thanks for quick reply @Manish 

Your solution is awesome but can you share your code please ?
It will be easy for me to implement in my project. :-)

**Comment by umutdonmez8** [comment]
Hi,

I have a question about this background issue. In swiftLocation documentation `Location.allowsBackgroundEvents = true` code writes for activate background location updates. I integrate SwiftLocation to my new project but, there is not any variable to set `allowsBackgroundEvents`

When I am trying to get location there is a log like
`A new request is added to the queue [LOC:826CB3FC-F0BD-4CB8-B8E2-EB6B598BE02F] - Acc=Room, Fq=Significant. (Status=running, Queued=true)
oYn4pRVBj3e56KTO0QXIhgABzT32
An existing request was removed from the queue [LOC:826CB3FC-F0BD-4CB8-B8E2-EB6B598BE02F] - Acc=Room, Fq=Significant. (Status=idle, Queued=false)
Location monitoring failed due to an error backgroundModeNotSet`

In my info.plist I insert the required background modes and I also open Location updates in Background Modes in Capabilities section. 

What can be the problem ?

Thanks for any help


My code is below: 

`//Taking Location

        Location.onAddNewRequest = { req in
            print("A new request is added to the queue \(req)")
        }
        Location.onRemoveRequest = { req in
            print("An existing request was removed from the queue \(req)")
        }
        
        
        let x = Location.getLocation(accuracy: .room, frequency: .significant, success: { (_, location) in
            print("A new update of location is available: \(location)")
            let longitude = location.coordinate.longitude
            let latitude = location.coordinate.latitude
            self.firebaseManager.setLocation(uid: uid!, longitude: longitude, latitude: latitude)
            
        }) { (request, last, error) in
            request.cancel() // stop continous location monitoring on error
            print("Location monitoring failed due to an error \(error)")
        }
        x.register(observer: LocObserver.onAuthDidChange(.main, { (request, oldAuth, newAuth) in
            print("Authorization moved from \(oldAuth) to \(newAuth)")
        }))

        
        //taking Location end`
