### ISSUE TITLE
iTunes Connect rejects builds because NSBluetoothPeripheralUsageDescription is required

### ISSUE THREAD

**Issue by robbiet480** [malcommac/SwiftLocation#79]
I just submitted a build to iTunes Connect that was rejected. The email I received stated:

`This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothPeripheralUsageDescription key with a string value explaining to the user how the app uses this data.`

I looked through all my source including Pods. The only project that has any mention of (Core) Bluetooth is SwiftLocation in [BeaconsManager.swift](https://github.com/malcommac/SwiftLocation/blob/master/src/BeaconsManager.swift). Need a workaround to get builds submitted again. For now, I manually removed all mentions in my Pods.

**Comment by malcommac** [comment]
Hi @robbiet480; thank you for your report. Yeah SwiftLocation also works to wrap BT features as like it does for CoreLocation.
However I can't think a final solution for this problem (other than fork and remove manually BeaconsManager and related classes).
Maybe a pre-processor macros to exclude it manually at compile time?

**Comment by robbiet480** [comment]
@malcommac I suggest removing the Bluetooth stuff and requiring that it be included via a Cocoapods Subspec. That's what PromiseKit did when I reported the same issue yesterday.

**Comment by malcommac** [comment]
Have you got some info about how to accomplish it?

**Comment by robbiet480** [comment]
@malcommac Not much. I can point you to how PromiseKit implemented it: [here](https://github.com/PromiseKit/UIKit/commit/61bd56304f5c9b4e71c17a89040839868e039269).

**Comment by zabolotiny** [comment]
Hey Guys, any status update regarding this issue? I am going to use SwiftLocation in my project and i don't want to be rejected...

**Comment by malcommac** [comment]
If you need to post the update right now my suggestion is to copy manually all files related to Location in your project:

```
HeadingRequest.swift
LocationManager.swift
LocationRequest.swift
VisitRequest.swift
Commons.swift
```

I need to investigate in it but right now I've not enough time (I'll see it the next week).

**Comment by zabolotiny** [comment]
Hey Daniele, thanks for the fast response and for the provided solution!

**Comment by ServicePal** [comment]
We ran into the same issue with another location library we are using. We simply re-submitted the app with NSBluetoothPeripheralUsageDescription set and got approved right away. In our case, the library optionally works with Bluetooth devices for better GPS tracking. We haven't turned that on, so the NSBluetoothPeripheralUsageDescription is never shown to the user.

Starting in iOS 10, your Info.plist file must include a purpose string, for display in the permission alert, for each such item. If your app attempts to access a protected item without you having provided a corresponding purpose string, your app exits.

We also had to add descriptions for Camera usage, Contacts etc.

https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/ExpectedAppBehaviors/ExpectedAppBehaviors.html#//apple_ref/doc/uid/TP40007072-CH3-SW6

**Comment by robbiet480** [comment]
@malcommac [Here's](https://github.com/nickoneill/PermissionScope/issues/194#issuecomment-248424690) an update that the author of PermissionScope got directly from Apple with a suggested fix.

**Comment by Jeehut** [comment]
I find the solution used by the Permission library very elegant (has both a solution for CocoaPods and Carthage) – while the CocoaPods solution is relatively easy (subspecs) the Carthage one is a bit more work, but I really like their approach. Here's what to do from the framework users perspective:
https://github.com/delba/Permission#configuration

**Comment by JRG-Developer** [comment]
How about creating sub specs in the pod spec, e.g. separating out bluetooth-required classes there?

This would at least solve the problem for everyone installing via CocoaPods, which I imagine is most/many consumers?

I'll try to find time to look at how feasible this is based on classes already there.

Best case: it would simply require moving classes around into different directories to support this.
Worst case: not possible depending on how intermixed functionality is...?

Would you be open to a PR that does this, if possible?

**Comment by malcommac** [comment]
I'm working on a new version on 2.0 branch; however this is a common issue I would resolve before moving forward. Location and Bluetooth modules are indipendent so if you know how to move them to a subspecs I'll be more than happy to accept a PR. Otherwise I'll remove BT monitoring from current spec.

**Comment by malcommac** [comment]
1.2.0 temporary remove it.
We will come with a more final solution before 2.0.0.
