### ISSUE TITLE
CocoaPods + Xcode 8 error

### ISSUE THREAD

**Issue by lfarah** [malcommac/SwiftLocation#81]
Got an error when trying to install SwiftLocation:
# Podfile

``` ruby
pod 'SwiftLocation', '>= 1.1.0'
```
# Error

[!] /usr/local/bin/git clone https://github.com/malcommac/SwiftLocation.git /var/folders/4b/dcgjrm3n3_3gh45gk237vx5c0000gn/T/d20160914-28528-1fe4wov --template= --single-branch --depth 1 --branch 1.1.0

Cloning into '/var/folders/4b/dcgjrm3n3_3gh45gk237vx5c0000gn/T/d20160914-28528-1fe4wov'...
warning: Could not find remote branch 1.1.0 to clone.
fatal: Remote branch 1.1.0 not found in upstream origin

```
```

**Comment by malcommac** [comment]
Let's try again and tell me if it works plz :)

**Comment by lfarah** [comment]
It works now. Thanks! 😄
