### ISSUE TITLE
cancel() calls itself recursively

### ISSUE THREAD

**Issue by gbtommasi** [malcommac/SwiftLocation#82]
Hello, 
I want to stop location when application enters background or is killed, and start monitoring significant changes only. I am possibly doing something wrong, but if I cancel a request using request.cance(), it calls itself recursively a couple of hundredth thousand times and the app crashes here in LocationRequest:

```
public func cancel() {
        self.cancel()
}
```

this happens in Swift 2.3 and 2.2 branches.

**Comment by malcommac** [comment]
Thank you for your report. Just fixed in 8a880f3bb8f8b64e1910f148c362ff588e8e0ce0.
