### ISSUE TITLE
cant run in xcode 7.3 it gives me 200+ errors ... please help

### ISSUE THREAD

**Issue by dhavalkmistry** [malcommac/SwiftLocation#83]
<img width="1196" alt="screen shot 2016-09-18 at 11 51 35 am" src="https://cloud.githubusercontent.com/assets/8543485/18613350/4f8ad112-7d96-11e6-8c70-429762ceef50.png">

**Comment by malcommac** [comment]
Swift 2.2 is here https://github.com/malcommac/SwiftLocation/tree/swift-2.2 (master branch is now swift 3). Check out the readme file for more infos.

**Comment by dhavalkmistry** [comment]
yes you were right i realised it later , and i have checked the swift 2.2
branch as well , and it runs in my xcode 7.3 , thanks man . and i wanted to
know that i have to track user location every 1km ,so if i use continuos
location tracking and if app is in suspended mode will it work in suspended
mode as well , please help me with this as i have to complete this
functionality asap.
