### ISSUE TITLE
Location not updating on launch

### ISSUE THREAD

**Issue by sagaya** [malcommac/SwiftLocation#85]
Here is the code am using 

``` swift
        Location.getLocation(withAccuracy: Accuracy.Neighborhood, onSuccess: { (location) in

            LATITUDE = location.coordinate.latitude
            LONGITUDE = location.coordinate.longitude

            print(location.coordinate.latitude)
            print(location.coordinate.longitude)


            }) { (location, error) in
                print(error)
        }
```

The code is in my `didFinishLaunchingWithOptions` because i want to update the location each time the app is lanched but it is crashing the app on launch it is not getting the location

**Comment by malcommac** [comment]
Have you already set `NSLocationAlwaysUsageDescription` or `NSLocationWhenInUseUsageDescription` in your app's Info.plist?

**Comment by sagaya** [comment]
Yes i have i set the two

**Comment by sagaya** [comment]
And i got this in the log `Location to Allowed
Error Domain=kCLErrorDomain Code=0 "(null)"
Location manager error: The operation couldn’t be completed. (kCLErrorDomain error 0.)`

**Comment by sagaya** [comment]
Ok the simulator is the problem had to set new current location
