### ISSUE TITLE
Using google as Reverse Location service throws runtime exception

### ISSUE THREAD

**Issue by Dharin-shah** [malcommac/SwiftLocation#89]
```swift
locationRequest = Location.getLocation(withAccuracy: .block, frequency: .oneShot, timeout: 30, onSuccess: { (location) in
                print(location)
                Location.reverse(location: location, using: ReverseService.google, onSuccess: { (placemark) in
                    DispatchQueue.main.async {
                        self.endLoading()
                    }
                    print(placemark.addressDictionary)
                    }, onError: { (error) in
                        /*
                         DispatchQueue.main.async {
                         self.endLoading()
                         self.handleError()
                         }*/
                        print(error)
                }).start()
                }, onError: { (lastLocation, error) in
                    self.endLoading()
                    print(lastLocation)
                    print(error)
            })
```

**And the Error**

> 2016-10-21 13:35:59.645 myapp-dev[5483:3234114] -[__NSCFLocalDataTask start]: unrecognized selector sent to instance 0x146d6b580
> 2016-10-21 13:35:59.648 myapp-dev[5483:3234114] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFLocalDataTask start]: unrecognized selector sent to instance 0x146d6b580'
> **\* First throw call stack:
> (0x183f22db0 0x183587f80 0x183f29c4c 0x183f26bec 0x183e24c5c 0x102310cc4 0x102310c80 0x1004ee7e4 0x102331ac4 0x102332a0c 0x1023257c0 0x10231ed84 0x1024d82bc 0x1023254f0 0x10232585c 0x18ac808b8 0x18ac7caac 0x18ac76e48 0x183ed8f84 0x183ed88bc 0x183ed6d04 0x183e00c50 0x1856e8088 0x1890ee088 0x100370218 0x18399e8b8)
> libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by malcommac** [comment]
You don't need to call `.start()` on  `Location.reverse` returned object , it's called automatically.
However there was a bug with Swift 3.1 where `URLSessionTask` does not seem include our extension.
Actually I've encapsulated `URLSessionTask` in a generic `NetworkTask` and it now works fine.
That's the commit.
https://github.com/malcommac/SwiftLocation/commit/8222a9336a3b38fdd3c8bb557866e58850513551

It will be included with 1.1.1
