### ISSUE TITLE
Using @discardableResult as result object for tasks

### ISSUE THREAD

**Issue by Craytor** [malcommac/SwiftLocation#90]
I am getting the following warning (and I don't like warnings), and I'm not sure how to get rid of it.

![](http://shots.tjyouschak.me/vtJHvH/Screen-Shot-2016-10-24-10-01-56.png)

Is this normal, or better yet, how should I handle the error?
Many thanks!

**Comment by malcommac** [comment]
you can use 

``` swift
let _ = Location.getLocation...
```

to silent the warning.
However I mark it as an enhancement because we should use `@discardableResult` for these function since Swift 3.

**Comment by Craytor** [comment]
Ah, thanks! That silenced it.

**Comment by malcommac** [comment]
Since 2.0.1 all requests allows @discardableResults.
Please notice: while the overall behaviour is the same, since 2.x branch some API names are changed. Nothing dramatic 👍
