### ISSUE TITLE
Value of type 'Request' has no member 'stop'

### ISSUE THREAD

**Issue by happiehappie** [malcommac/SwiftLocation#92]
I was following the documentation literally and I got the error in the title

                let request = Location.getLocation(withAccuracy: .city, frequency: .oneShot, timeout: 50, onSuccess: { (location) in
                    // You will receive at max one event if desidered accuracy can be achieved; this because you have set .OneShot as frequency.
                }) { (lastValidLocation, error) in
                }
                request.stop()

**Comment by happiehappie** [comment]
I'm using Swift 3 if it matters

**Comment by chengsam** [comment]
I think the method is `cancel()`

**Comment by malcommac** [comment]
Yeah it was cancel().
Fixed doc.
Thanks.
