### ISSUE TITLE
getLocation() does not work 

### ISSUE THREAD

**Issue by mrfarukturgut** [malcommac/SwiftLocation#93]
Hi, 

I am trying to build Location Manager based on SwiftLocation. I made a simple function which you can find below, but it completely does not work. I am not sure it is because of the library or any other thing. The interesting point is when I call this function from ViewController which appears first, 
Allow request for Location Services pops up but disappears right away. Any help will make me so appreciated. 

```
let manager = LocationManager()
        manager.getLocation(withAccuracy: .city, frequency: .continuous, onSuccess: { loc in
            print(loc)
            }, onError: {(loc, error) in
                print(error)
        })
```

By the way I am working on simulator, Location updates in capabilities is on, Default Location is set as London, England in Scheme.

**Comment by O-mkar** [comment]
Same here i'm having this issue 
Location manager error: The operation couldn’t be completed. (kCLErrorDomain error 0.)

**Comment by Alex293** [comment]
Did you set the keys in the plist ?

**Comment by mrfarukturgut** [comment]
I have solved the issue. yes I had set the keys in the plist for location but it was not work. I have changed the library with a little simpler one (https://github.com/lypiut/WhereAmI) that i use because i just need to get current location. Then deleted the keys in the plist, set them again afterwards. Now it is working.
