### ISSUE TITLE
While location is always getlocation doesn't work

### ISSUE THREAD

**Issue by O-mkar** [malcommac/SwiftLocation#95]
I tried to request while permission is in always mode and it stops working when i request the second time but first time works. but while in use works well.

**Comment by malcommac** [comment]
I think I don't understand your workflow. Can you explain it better please?
Thanks.

**Comment by O-mkar** [comment]
@malcommac 
When Location is "Always": When I request Location of a user using getlocation the First request I make give me correct results but in a second request I make give me a null response even lastValidLoc is null it doesn't work at all till I restart the app.

**Comment by murad1981** [comment]
same thing happens here, but my setup is `getLocation(withAccuracy: .block, frequency: .byDistanceIntervals(meters: 1) `

so I needed to fire the success block each time I travel a distance of 1 meter, is there something special should I do in order to get it to work ?

p.s. I tested it on iPhone 6Plus iOS 10 device

**Comment by tejasverixo** [comment]
i tried same thing but it's not working. my setup is `getLocation(withAccuracy: .house, frequency: .byDistanceIntervals(meters: 50)`

so I needed to fire the success block each time I travel a distance of 50 meter. 
Plz advice.

**Comment by malcommac** [comment]
Since 2.0 you can set a frequency with `continous` and set the Request's property `minimumDistance`.
Please notice: while the overall behaviour is the same, since 2.x branch some API names are changed. Nothing dramatic 👍
