### ISSUE TITLE
Namespace conflict

### ISSUE THREAD

**Issue by ogezue** [malcommac/SwiftLocation#96]
Would it be possible to rename Location into SwiftLocation to avoid Namespace conflicts? Location is to generic and in my app I currently have to do some workarounds now.
Same for Request.

**Comment by jovobe** [comment]
> Would it be possible to rename Location into SwiftLocation to avoid Namespace conflicts? Location is to generic and in my app I currently have to do some workarounds now.
Same for Request.

I have the same issues and the following worked for me:
```
import SwiftLocation
[...]
SwiftLocation.Location.getLocation...```

**Comment by ogezue** [comment]
Yes - this is working, but I wouldn't use such prominent names in my framework.

**Comment by jovobe** [comment]
> I wouldn't use such prominent names in my framework

I absolutely agree with You! I just wanted to show You a small workaround until a fix is released.
