### ISSUE TITLE
Energy consumption

### ISSUE THREAD

**Issue by ogezue** [malcommac/SwiftLocation#97]
My use case is to monitor the time when the user traveled (car, train, etc.) so my app is constantly running in background.

With this setting I have an concumption of round abeout 15-20% on an iPhone 6s
```
self.locationManager.requestAlwaysAuthorization()
self.locationManager.desiredAccuracy = kCLLocationAccuracyHundredMeters
self.locationManager.distanceFilter = 400
self.locationManager.pausesLocationUpdatesAutomatically = false
self.locationManager.allowsBackgroundLocationUpdates = true
self.locationManager.activityType = .other
```

I tried the Cintric SDK and they perform significantly better with a usage of 1%.
https://github.com/cintric/cintric-locate-tester. If you want to test Cintric make sure you add 
`[Cintric setLegacyLocationTrackingEnabled:true];` into the `didFinishLaunching` method. 

Currently I'm evaluating your framework. Do you have statistics about energy consumption in background? Perhaps you have some ideas how Cintric is achieving this? I can not use them in my app because the are sending the users location into the cloud.

**Comment by malcommac** [comment]
Since SwiftLocation 2.0 I've rewrote the entire part of location manager. Give it a try (some APIs call are changed but it's a matter of names, nothing more).
You can track the current status of the LocationTracker class by printing the description of the object itself.
