### ISSUE TITLE
Multiple request at the same time

### ISSUE THREAD

**Issue by Alex293** [malcommac/SwiftLocation#98]
Hi, just wanted to know if I have like 3 or 4 exactly same requests at the same time but in different controllers will they get the same result ? will it consume more resource or the manager is designed to handle this case ?

**Comment by malcommac** [comment]
Hi,
The overall energy consumption is based upon the highest level of precision between all running tasks. And yeah if two requests are created with the same settings you will receive the same results in both of them.
