### ISSUE TITLE
Canceling requests does not stop location tracking resulting in battery drain

### ISSUE THREAD

**Issue by ghost** [malcommac/SwiftLocation#99]
We noticed considerable battery drain while evaluating SwiftLocation: our setup creates a one shot request for the current location, then cancels this request. Even after adding cancelation of all requests on several exit points (viewcontroller, appDelegate) location monitoring is still active and  draining the battery.
I don't have the time to look for the underlying cause myself as we will take SwiftLocation back out of our codebase, but still wanted to provide this information.

**Comment by malcommac** [comment]
Hi @halkmund,
Are you sure you are talking about a single one shot request?
Also you don't need to stop the request 

```swift
let _ = Location.getLocation(withAccuracy: .city, frequency: .oneShot, timeout: nil, onSuccess: { (loc) in
  print("loc \(loc)")
}) { (last, err) in
  print("err \(err)")
}
```

Just after the request CPU usage is zero:
Can you tell me more about it?

<img width="259" alt="screen shot 2016-12-07 at 11 53 01" src="https://cloud.githubusercontent.com/assets/235645/20964903/c45ed5bc-bc73-11e6-8206-53b89876fce0.png">

**Comment by ghost** [comment]
Yes, one shot request.

We cancel the request onSuccess and/or failure. Then we also use stopAllLocationRequests. I have noticed that stopAllLocationRequests needs an error in order for the request to be actually canceled .. We did not supply an error in our setup. But then again, calling cancel on our request should trigger the remove() on the LocationManager. Which in turn should trigger the updateLocationUpdateService() method. Which should stop the CLLocation updates.

If I find the time I will debug and see what happens.

Maybe stopAllLocationRequests should actually stop the requests, even if no error is provided and pause = false. Just for clarity.

Thanks for your reply!

**Comment by malcommac** [comment]
I've fixed it in 2.x branch.
When you create a new request via `Location` func it will be added automatically and started. You can however `pause()` or `cancel()` it at any time. Global overall settings and consuption will be adjusted automatically based upon currently running request.
Please notice: while the overall behaviour is the same, since 2.x branch some API names are changed. Nothing dramatic 👍
